export type Category =
  | 'Crypto'
  | 'Sports'
  | 'Finance'
  | 'Science'
  | 'Tech'
  | 'Economics'
  | 'Stocks'
  | 'AI'
  | 'Climate'

export type MarketType = 'UP_OR_DOWN' | 'MULTIPLE_CHOICE' | 'RANGE' | 'THRESHOLD' | 'DATE'

export type Market = {
  id: string
  question: string
  category: Category
  marketType: MarketType
  yes: number // 0-100 probability of YES
  volume: string
  liquidity: string
  participants: string
  timeLeft: string
  trend: 'up' | 'down'
  chart: number[]
  verified: boolean
  icon: string // emoji-free short token label shown in the colored chip
  accent: string // hex color for the icon chip
}

export const CATEGORIES: Category[] = [
  'Crypto',
  'Economics',
  'Sports',
  'Finance',
  'Stocks',
  'Science',
  'Tech',
  'AI',
  'Climate',
]

function series(seed: number, up: boolean): number[] {
  const pts: number[] = []
  let v = 40 + (seed % 20)
  for (let i = 0; i < 24; i++) {
    const drift = up ? 0.8 : -0.6
    v += Math.sin(i * 0.6 + seed) * 6 + drift + (i % 3 === 0 ? 2 : -1)
    pts.push(Math.max(8, Math.min(92, v)))
  }
  return pts
}

export const MARKETS: Market[] = [
  {
    id: 'btc-200k',
    question: 'Bitcoin above $70,000 on July 24?',
    category: 'Crypto',
    marketType: 'UP_OR_DOWN',
    yes: 51,
    volume: '$18.4m',
    liquidity: '$6.2m',
    participants: '28.3K',
    timeLeft: '24 Jul · 07:00 AM',
    trend: 'up',
    chart: series(3, true),
    verified: true,
    icon: 'BTC',
    accent: '#f7931a',
  },
  {
    id: 'fed-decision',
    question: 'Fed Decision in July?',
    category: 'Economics',
    marketType: 'MULTIPLE_CHOICE',
    yes: 71,
    volume: '$91.7m',
    liquidity: '$28.2m',
    participants: '14 markets',
    timeLeft: '29 Jul · 07:00 AM',
    trend: 'up',
    chart: series(8, true),
    verified: true,
    icon: 'FED',
    accent: '#20c997',
  },
  {
    id: 'xrp-range',
    question: 'XRP price between $1.05 - $1.20 on July 25?',
    category: 'Crypto',
    marketType: 'RANGE',
    yes: 55,
    volume: '$3.6m',
    liquidity: '$1.2m',
    participants: '8.9K',
    timeLeft: '25 Jul · 23:59',
    trend: 'up',
    chart: series(21, true),
    verified: true,
    icon: 'XRP',
    accent: '#23f7dd',
  },
  {
    id: 'xrp-threshold',
    question: 'XRP above $1.20 anytime on July 25?',
    category: 'Crypto',
    marketType: 'THRESHOLD',
    yes: 38,
    volume: '$2.8m',
    liquidity: '$910K',
    participants: '6.2K',
    timeLeft: '25 Jul · 23:59',
    trend: 'down',
    chart: series(14, false),
    verified: true,
    icon: 'XRP',
    accent: '#23f7dd',
  },
  {
    id: 'xrp-date',
    question: 'XRP price on July 31, 2026?',
    category: 'Crypto',
    marketType: 'DATE',
    yes: 62,
    volume: '$8.1m',
    liquidity: '$2.9m',
    participants: '11.7K',
    timeLeft: '31 Jul 2026 · 00:00 UTC',
    trend: 'up',
    chart: series(30, true),
    verified: true,
    icon: 'XRP',
    accent: '#23f7dd',
  },
  {
    id: 'brazil-copa',
    question: 'Will Brazil win the Copa 2026?',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 48,
    volume: '$6.2m',
    liquidity: '$1.8m',
    participants: '9.1K',
    timeLeft: '15 Jun 2026',
    trend: 'down',
    chart: series(41, false),
    verified: true,
    icon: 'BR',
    accent: '#febe10',
  },
  {
    id: 'cpi-economy',
    question: 'US CPI above 3% in July?',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 37,
    volume: '$3.8m',
    liquidity: '$1.1m',
    participants: '5.3K',
    timeLeft: '31 Jul · 08:30 AM',
    trend: 'down',
    chart: series(52, false),
    verified: true,
    icon: 'CPI',
    accent: '#3b82f6',
  },
  {
    id: 'nvda-stocks',
    question: 'NVIDIA above $150 on Aug 15?',
    category: 'Stocks',
    marketType: 'UP_OR_DOWN',
    yes: 55,
    volume: '$2.3m',
    liquidity: '$690K',
    participants: '4.2K',
    timeLeft: '15 Aug · 07:00 AM',
    trend: 'up',
    chart: series(63, true),
    verified: true,
    icon: 'NVDA',
    accent: '#76b900',
  },
  // Economics Markets
  {
    id: 'us-inflation-2026',
    question: 'US Inflation below 2% by Q4 2026',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 35,
    volume: '$2.1m',
    liquidity: '$650K',
    participants: '3.8K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(10, false),
    verified: true,
    icon: 'INF',
    accent: '#8b5cf6',
  },
  {
    id: 'us-gdp-growth',
    question: 'US GDP Growth above 3%',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 48,
    volume: '$1.8m',
    liquidity: '$540K',
    participants: '3.2K',
    timeLeft: '30 Jun 2026',
    trend: 'up',
    chart: series(11, true),
    verified: true,
    icon: 'GDP',
    accent: '#06b6d4',
  },
  {
    id: 'us-unemployment-4',
    question: 'US Unemployment below 4%',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 52,
    volume: '$1.5m',
    liquidity: '$450K',
    participants: '2.9K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(12, true),
    verified: true,
    icon: 'UMP',
    accent: '#10b981',
  },
  {
    id: 'china-gdp',
    question: 'China GDP exceed expectations',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 41,
    volume: '$1.2m',
    liquidity: '$360K',
    participants: '2.4K',
    timeLeft: '30 Jun 2026',
    trend: 'down',
    chart: series(13, false),
    verified: true,
    icon: 'CHN',
    accent: '#ef4444',
  },
  {
    id: 'eurozone-recession',
    question: 'Eurozone enters recession',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 28,
    volume: '$980K',
    liquidity: '$294K',
    participants: '1.8K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(14, false),
    verified: true,
    icon: 'EUR',
    accent: '#0ea5e9',
  },
  {
    id: 'japan-rates',
    question: 'Japan raises interest rates again',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 62,
    volume: '$1.3m',
    liquidity: '$390K',
    participants: '2.6K',
    timeLeft: '30 Sep 2026',
    trend: 'up',
    chart: series(15, true),
    verified: true,
    icon: 'JPN',
    accent: '#ec4899',
  },
  {
    id: 'indonesia-bi-cut',
    question: 'Indonesia BI Rate cut before Q1 2027',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 55,
    volume: '$850K',
    liquidity: '$255K',
    participants: '2.1K',
    timeLeft: '31 Mar 2027',
    trend: 'up',
    chart: series(16, true),
    verified: true,
    icon: 'IDN',
    accent: '#f59e0b',
  },
  {
    id: 'oil-100',
    question: 'Oil price above $100/barrel',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 38,
    volume: '$1.4m',
    liquidity: '$420K',
    participants: '3.1K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(17, false),
    verified: true,
    icon: 'OIL',
    accent: '#1f2937',
  },
  {
    id: 'gold-4000',
    question: 'Gold above $4,000',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 72,
    volume: '$2.2m',
    liquidity: '$660K',
    participants: '4.5K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(18, true),
    verified: true,
    icon: 'AU',
    accent: '#fbbf24',
  },
  {
    id: 'usd-index-110',
    question: 'US Dollar Index above 110',
    category: 'Economics',
    marketType: 'UP_OR_DOWN',
    yes: 45,
    volume: '$1.6m',
    liquidity: '$480K',
    participants: '3.3K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(19, false),
    verified: true,
    icon: 'USD',
    accent: '#22c55e',
  },
  // Financials Markets
  {
    id: 'apple-5t',
    question: 'Apple market cap reaches $5T',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 68,
    volume: '$3.1m',
    liquidity: '$930K',
    participants: '5.2K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(20, true),
    verified: true,
    icon: 'AAPL',
    accent: '#a1a1a1',
  },
  {
    id: 'msft-700',
    question: 'Microsoft above $700/share',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 71,
    volume: '$2.8m',
    liquidity: '$840K',
    participants: '4.8K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(21, true),
    verified: true,
    icon: 'MSFT',
    accent: '#00a4ef',
  },
  {
    id: 'nvda-beats',
    question: 'NVIDIA quarterly revenue beats estimates',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 74,
    volume: '$2.6m',
    liquidity: '$780K',
    participants: '4.5K',
    timeLeft: '30 Sep 2026',
    trend: 'up',
    chart: series(22, true),
    verified: true,
    icon: 'NVDA',
    accent: '#76b900',
  },
  {
    id: 'tesla-500',
    question: 'Tesla above $500/share',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 52,
    volume: '$2.2m',
    liquidity: '$660K',
    participants: '4.1K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(23, true),
    verified: true,
    icon: 'TSLA',
    accent: '#e82127',
  },
  {
    id: 'meta-ai-device',
    question: 'Meta launches new AI device',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 81,
    volume: '$1.9m',
    liquidity: '$570K',
    participants: '3.7K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(24, true),
    verified: true,
    icon: 'META',
    accent: '#0a66c2',
  },
  {
    id: 'amzn-beats',
    question: 'Amazon revenue beats Wall Street estimates',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 76,
    volume: '$2.3m',
    liquidity: '$690K',
    participants: '4.3K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(25, true),
    verified: true,
    icon: 'AMZN',
    accent: '#ff9900',
  },
  {
    id: 'nflx-subs',
    question: 'Netflix subscriber growth exceeds expectations',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 69,
    volume: '$1.7m',
    liquidity: '$510K',
    participants: '3.5K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(26, true),
    verified: true,
    icon: 'NFLX',
    accent: '#e50914',
  },
  {
    id: 'ibit-200b',
    question: 'BlackRock Bitcoin ETF AUM above $200B',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 58,
    volume: '$2.4m',
    liquidity: '$720K',
    participants: '4.6K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(27, true),
    verified: true,
    icon: 'IBIT',
    accent: '#1f2937',
  },
  {
    id: 'sp500-7000',
    question: 'S&P500 closes above 7,000',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 65,
    volume: '$3.2m',
    liquidity: '$960K',
    participants: '5.4K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(28, true),
    verified: true,
    icon: 'SPX',
    accent: '#003478',
  },
  {
    id: 'nasdaq-ath',
    question: 'Nasdaq hits new all-time high',
    category: 'Finance',
    marketType: 'UP_OR_DOWN',
    yes: 73,
    volume: '$2.9m',
    liquidity: '$870K',
    participants: '5.1K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(29, true),
    verified: true,
    icon: 'NDX',
    accent: '#fff4f0',
  },
  // Tech & Science Markets (same as Financials for now)
  {
    id: 'gpt6-release',
    question: 'OpenAI releases GPT-6',
    category: 'Tech',
    marketType: 'UP_OR_DOWN',
    yes: 64,
    volume: '$2.7m',
    liquidity: '$810K',
    participants: '4.9K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(30, true),
    verified: true,
    icon: 'GPT',
    accent: '#10a37f',
  },
  {
    id: 'gemini-ultra',
    question: 'Google Gemini Ultra surpasses GPT benchmark',
    category: 'Tech',
    marketType: 'UP_OR_DOWN',
    yes: 53,
    volume: '$1.9m',
    liquidity: '$570K',
    participants: '3.8K',
    timeLeft: '30 Jun 2026',
    trend: 'up',
    chart: series(31, true),
    verified: true,
    icon: 'GEM',
    accent: '#4285f4',
  },
  {
    id: 'claude-100m',
    question: 'Claude reaches 100M monthly users',
    category: 'Tech',
    marketType: 'UP_OR_DOWN',
    yes: 70,
    volume: '$2.2m',
    liquidity: '$660K',
    participants: '4.2K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(32, true),
    verified: true,
    icon: 'CLD',
    accent: '#c4a26d',
  },
  {
    id: 'ai-movie-oscar',
    question: 'AI-generated movies win an Oscar',
    category: 'Tech',
    marketType: 'UP_OR_DOWN',
    yes: 22,
    volume: '$1.1m',
    liquidity: '$330K',
    participants: '2.3K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(33, false),
    verified: true,
    icon: 'OSC',
    accent: '#fbbf24',
  },
  {
    id: 'copilot-50m',
    question: 'GitHub Copilot reaches 50M users',
    category: 'Tech',
    marketType: 'UP_OR_DOWN',
    yes: 76,
    volume: '$2.4m',
    liquidity: '$720K',
    participants: '4.7K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(34, true),
    verified: true,
    icon: 'GHP',
    accent: '#1f2937',
  },
  // AI Markets
  {
    id: 'ai-support-20pct',
    question: 'AI agents replace 20% of customer support jobs',
    category: 'AI',
    marketType: 'UP_OR_DOWN',
    yes: 61,
    volume: '$2.1m',
    liquidity: '$630K',
    participants: '4.0K',
    timeLeft: '31 Dec 2027',
    trend: 'up',
    chart: series(35, true),
    verified: true,
    icon: 'AI',
    accent: '#8b5cf6',
  },
  {
    id: 'oss-beats-gpt',
    question: 'Open-source model beats GPT benchmark',
    category: 'AI',
    marketType: 'UP_OR_DOWN',
    yes: 67,
    volume: '$2.3m',
    liquidity: '$690K',
    participants: '4.4K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(36, true),
    verified: true,
    icon: 'OSS',
    accent: '#0ea5e9',
  },
  {
    id: 'ai-regulation-us',
    question: 'AI regulation passes in the US',
    category: 'AI',
    marketType: 'UP_OR_DOWN',
    yes: 45,
    volume: '$1.8m',
    liquidity: '$540K',
    participants: '3.5K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(37, false),
    verified: true,
    icon: 'REG',
    accent: '#ef4444',
  },
  {
    id: 'ai-market-1t',
    question: 'AI market exceeds $1 trillion',
    category: 'AI',
    marketType: 'UP_OR_DOWN',
    yes: 82,
    volume: '$3.4m',
    liquidity: '$1.02m',
    participants: '6.1K',
    timeLeft: '31 Dec 2027',
    trend: 'up',
    chart: series(38, true),
    verified: true,
    icon: 'MKT',
    accent: '#10b981',
  },
  {
    id: 'humanoid-robots',
    question: 'Humanoid AI robots enter mass production',
    category: 'AI',
    marketType: 'UP_OR_DOWN',
    yes: 48,
    volume: '$1.5m',
    liquidity: '$450K',
    participants: '3.0K',
    timeLeft: '31 Dec 2027',
    trend: 'up',
    chart: series(39, true),
    verified: true,
    icon: 'RBT',
    accent: '#f59e0b',
  },
  // Climate Markets
  {
    id: 'co2-decrease',
    question: 'Global CO₂ emissions decrease year-over-year',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 32,
    volume: '$1.3m',
    liquidity: '$390K',
    participants: '2.8K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(40, false),
    verified: true,
    icon: 'CO2',
    accent: '#059669',
  },
  {
    id: 'hurricane-forecast',
    question: 'Hurricane season exceeds NOAA forecast',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 55,
    volume: '$1.1m',
    liquidity: '$330K',
    participants: '2.5K',
    timeLeft: '30 Nov 2026',
    trend: 'up',
    chart: series(41, true),
    verified: true,
    icon: 'HUR',
    accent: '#0369a1',
  },
  {
    id: 'arctic-ice-low',
    question: 'Arctic sea ice reaches record low',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 71,
    volume: '$1.8m',
    liquidity: '$540K',
    participants: '3.6K',
    timeLeft: '31 Aug 2026',
    trend: 'up',
    chart: series(42, true),
    verified: true,
    icon: 'ARC',
    accent: '#0ea5e9',
  },
  {
    id: 'solar-exceeds-coal',
    question: 'Solar energy exceeds coal globally',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 66,
    volume: '$2.0m',
    liquidity: '$600K',
    participants: '3.9K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(43, true),
    verified: true,
    icon: 'SOL',
    accent: '#fbbf24',
  },
  {
    id: 'ev-sales-50pct',
    question: 'EV sales exceed 50% of new cars',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 58,
    volume: '$1.9m',
    liquidity: '$570K',
    participants: '3.7K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(44, true),
    verified: true,
    icon: 'EV',
    accent: '#10b981',
  },
  {
    id: 'renewable-capacity',
    question: 'Global renewable capacity surpasses target',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 73,
    volume: '$2.2m',
    liquidity: '$660K',
    participants: '4.3K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(45, true),
    verified: true,
    icon: 'REN',
    accent: '#059669',
  },
  {
    id: 'el-nino-ends',
    question: 'El Niño officially ends',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 62,
    volume: '$1.4m',
    liquidity: '$420K',
    participants: '2.9K',
    timeLeft: '30 Sep 2026',
    trend: 'up',
    chart: series(46, true),
    verified: true,
    icon: 'ENO',
    accent: '#d97706',
  },
  {
    id: 'la-nina-returns',
    question: 'La Niña returns before year end',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 48,
    volume: '$1.2m',
    liquidity: '$360K',
    participants: '2.6K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(47, false),
    verified: true,
    icon: 'LNA',
    accent: '#0369a1',
  },
  {
    id: 'carbon-credit-100',
    question: 'Carbon credit price above $100',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 51,
    volume: '$1.6m',
    liquidity: '$480K',
    participants: '3.2K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(48, true),
    verified: true,
    icon: 'CRB',
    accent: '#059669',
  },
  {
    id: 'temp-anomaly-17',
    question: 'Global temperature anomaly exceeds 1.7°C',
    category: 'Climate',
    marketType: 'UP_OR_DOWN',
    yes: 64,
    volume: '$1.7m',
    liquidity: '$510K',
    participants: '3.4K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(49, true),
    verified: true,
    icon: 'TMP',
    accent: '#ef4444',
  },
  // Sports Markets - Additional
  {
    id: 'real-madrid-ucl',
    question: 'Real Madrid wins Champions League',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 45,
    volume: '$1.8m',
    liquidity: '$540K',
    participants: '3.6K',
    timeLeft: '31 May 2026',
    trend: 'up',
    chart: series(50, true),
    verified: true,
    icon: 'RM',
    accent: '#ffffff',
  },
  {
    id: 'man-city-pl',
    question: 'Manchester City wins Premier League',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 52,
    volume: '$1.6m',
    liquidity: '$480K',
    participants: '3.3K',
    timeLeft: '31 May 2026',
    trend: 'up',
    chart: series(51, true),
    verified: true,
    icon: 'MC',
    accent: '#6cabde',
  },
  {
    id: 'brazil-wc',
    question: 'Brazil wins FIFA World Cup 2026',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 48,
    volume: '$2.4m',
    liquidity: '$720K',
    participants: '4.5K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(52, true),
    verified: true,
    icon: 'BR',
    accent: '#fbbf24',
  },
  {
    id: 'max-verstappen-f1',
    question: 'Max Verstappen wins Formula 1 Championship',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 71,
    volume: '$1.9m',
    liquidity: '$570K',
    participants: '3.7K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(53, true),
    verified: true,
    icon: 'F1',
    accent: '#003478',
  },
  {
    id: 'lakers-nba-finals',
    question: 'Lakers reach NBA Finals',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 38,
    volume: '$1.3m',
    liquidity: '$390K',
    participants: '2.8K',
    timeLeft: '31 May 2026',
    trend: 'down',
    chart: series(54, false),
    verified: true,
    icon: 'LAL',
    accent: '#552583',
  },
  {
    id: 'indonesia-wc',
    question: 'Indonesia qualifies for World Cup',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 22,
    volume: '$920K',
    liquidity: '$276K',
    participants: '2.1K',
    timeLeft: '15 Nov 2025',
    trend: 'down',
    chart: series(55, false),
    verified: true,
    icon: 'IDN',
    accent: '#ff0000',
  },
  {
    id: 'djokovic-wimbledon',
    question: 'Novak Djokovic wins Wimbledon',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 35,
    volume: '$1.1m',
    liquidity: '$330K',
    participants: '2.5K',
    timeLeft: '31 Jul 2026',
    trend: 'down',
    chart: series(56, false),
    verified: true,
    icon: 'WIM',
    accent: '#006241',
  },
  {
    id: 'mclaren-constructors',
    question: 'McLaren wins Constructors Championship',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 28,
    volume: '$980K',
    liquidity: '$294K',
    participants: '2.3K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(57, false),
    verified: true,
    icon: 'MCL',
    accent: '#ff8700',
  },
  {
    id: 'messi-20-goals',
    question: 'Lionel Messi scores 20+ goals this season',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 42,
    volume: '$1.2m',
    liquidity: '$360K',
    participants: '2.7K',
    timeLeft: '31 Dec 2026',
    trend: 'down',
    chart: series(58, false),
    verified: true,
    icon: 'LEO',
    accent: '#1f2937',
  },
  {
    id: 'ronaldo-1000-goals',
    question: 'Cristiano Ronaldo reaches 1,000 career goals',
    category: 'Sports',
    marketType: 'UP_OR_DOWN',
    yes: 58,
    volume: '$1.5m',
    liquidity: '$450K',
    participants: '3.1K',
    timeLeft: '31 Dec 2026',
    trend: 'up',
    chart: series(59, true),
    verified: true,
    icon: 'CR7',
    accent: '#ef4444',
  },
]

export const FEATURED = {
  tag: 'FEATURED EVENT',
  title: 'FIFA World Cup 2026',
  subtitle: 'Who will win the FIFA World Cup 2026?',
  cta: 'Trade Now',
}

export const OPEN_POSITIONS = [
  {
    id: 'btc-200k',
    question: 'BTC to reach $200K by Dec 31, 2025?',
    side: 'Yes',
    prob: 62,
    value: '$680.00',
    pnl: '+12.20%',
    up: true,
    meta: '3d left · 120.0 shares',
  },
  {
    id: 'eth-etf',
    question: 'ETH ETF approved by May 2024?',
    side: 'Yes',
    prob: 41,
    value: '$320.00',
    pnl: '+8.10%',
    up: true,
    meta: '12d left · 80.0 shares',
  },
]

export const RECENT_ACTIVITY = [
  {
    label: 'Bought Yes · BTC to $200K',
    time: '2m ago',
    amount: '-10.00 USDC',
    up: false,
  },
  {
    label: 'Sold No · SOL to $300',
    time: '1h ago',
    amount: '+15.20 USDC',
    up: true,
  },
  {
    label: 'Deposit · Wallet top-up',
    time: '5h ago',
    amount: '+250.00 USDC',
    up: true,
  },
]

export const SOURCES = [
  { name: 'CoinDesk', time: '2h ago' },
  { name: 'Bloomberg', time: '5h ago' },
  { name: 'NewsBTC', time: '1d ago' },
]
