// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markets_queries.sql

package dbqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarketsCatalogEvents = `-- name: CountMarketsCatalogEvents :one
SELECT COUNT(*)::BIGINT AS count
FROM markets_catalog_events
`

func (q *Queries) CountMarketsCatalogEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMarketsCatalogEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredMarketsRawUpstreamEvents = `-- name: DeleteExpiredMarketsRawUpstreamEvents :execrows
DELETE FROM markets_raw_upstream_events
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredMarketsRawUpstreamEvents(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMarketsRawUpstreamEvents, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestCatalogProjectionObservedAt = `-- name: GetLatestCatalogProjectionObservedAt :one
SELECT COALESCE(MAX(observed_at), TIMESTAMPTZ '1970-01-01 00:00:00+00')::TIMESTAMPTZ AS observed_at
FROM markets_catalog_events
`

func (q *Queries) GetLatestCatalogProjectionObservedAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestCatalogProjectionObservedAt)
	var observed_at pgtype.Timestamptz
	err := row.Scan(&observed_at)
	return observed_at, err
}

const getLatestMarketsHealth = `-- name: GetLatestMarketsHealth :one
SELECT market_id, token_id, algorithm_version, observed_at, freshness_state, components, created_at
FROM markets_market_health_snapshots
WHERE market_id = $1 AND token_id = $2
ORDER BY observed_at DESC
LIMIT 1
`

type GetLatestMarketsHealthParams struct {
	MarketID string `json:"market_id"`
	TokenID  string `json:"token_id"`
}

func (q *Queries) GetLatestMarketsHealth(ctx context.Context, arg GetLatestMarketsHealthParams) (MarketsMarketHealthSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestMarketsHealth, arg.MarketID, arg.TokenID)
	var i MarketsMarketHealthSnapshot
	err := row.Scan(
		&i.MarketID,
		&i.TokenID,
		&i.AlgorithmVersion,
		&i.ObservedAt,
		&i.FreshnessState,
		&i.Components,
		&i.CreatedAt,
	)
	return i, err
}

const getMarketIDByUpstreamToken = `-- name: GetMarketIDByUpstreamToken :one
SELECT o.market_id
FROM markets_catalog_outcomes o
INNER JOIN markets_catalog_markets m ON m.market_id = o.market_id
WHERE o.upstream_token_id = $1
  AND m.status = 'open'
`

func (q *Queries) GetMarketIDByUpstreamToken(ctx context.Context, upstreamTokenID string) (string, error) {
	row := q.db.QueryRow(ctx, getMarketIDByUpstreamToken, upstreamTokenID)
	var market_id string
	err := row.Scan(&market_id)
	return market_id, err
}

const getMarketsCatalogEvent = `-- name: GetMarketsCatalogEvent :one
SELECT event_id, id, upstream_id, upstream_source, slug, title, description, status, start_at, end_at, source, upstream_updated_at, content_hash, payload, observed_at, created_at, updated_at
FROM markets_catalog_events
WHERE event_id = $1
`

func (q *Queries) GetMarketsCatalogEvent(ctx context.Context, eventID string) (MarketsCatalogEvent, error) {
	row := q.db.QueryRow(ctx, getMarketsCatalogEvent, eventID)
	var i MarketsCatalogEvent
	err := row.Scan(
		&i.EventID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Source,
		&i.UpstreamUpdatedAt,
		&i.ContentHash,
		&i.Payload,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketsCatalogMarket = `-- name: GetMarketsCatalogMarket :one
SELECT market_id, id, upstream_id, upstream_source, event_id, condition_id, slug, question, description, status, end_at, enable_order_book, neg_risk, source, upstream_updated_at, content_hash, payload, observed_at, created_at, updated_at
FROM markets_catalog_markets
WHERE market_id = $1 OR condition_id = $1
`

func (q *Queries) GetMarketsCatalogMarket(ctx context.Context, marketID string) (MarketsCatalogMarket, error) {
	row := q.db.QueryRow(ctx, getMarketsCatalogMarket, marketID)
	var i MarketsCatalogMarket
	err := row.Scan(
		&i.MarketID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.EventID,
		&i.ConditionID,
		&i.Slug,
		&i.Question,
		&i.Description,
		&i.Status,
		&i.EndAt,
		&i.EnableOrderBook,
		&i.NegRisk,
		&i.Source,
		&i.UpstreamUpdatedAt,
		&i.ContentHash,
		&i.Payload,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketsCatalogRule = `-- name: GetMarketsCatalogRule :one
SELECT market_id, id, upstream_id, upstream_source, description, resolution_source_name, resolution_source_url, content_hash, upstream_updated_at, observed_at, created_at, updated_at
FROM markets_catalog_rules
WHERE market_id = $1
`

func (q *Queries) GetMarketsCatalogRule(ctx context.Context, marketID string) (MarketsCatalogRule, error) {
	row := q.db.QueryRow(ctx, getMarketsCatalogRule, marketID)
	var i MarketsCatalogRule
	err := row.Scan(
		&i.MarketID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.Description,
		&i.ResolutionSourceName,
		&i.ResolutionSourceUrl,
		&i.ContentHash,
		&i.UpstreamUpdatedAt,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketsLatestBook = `-- name: GetMarketsLatestBook :one
SELECT token_id, market_id, condition_id, freshness_state, freshness_reason, book_hash, upstream_timestamp, observed_at, snapshot, updated_at
FROM markets_market_data_latest
WHERE token_id = $1
`

func (q *Queries) GetMarketsLatestBook(ctx context.Context, tokenID string) (MarketsMarketDataLatest, error) {
	row := q.db.QueryRow(ctx, getMarketsLatestBook, tokenID)
	var i MarketsMarketDataLatest
	err := row.Scan(
		&i.TokenID,
		&i.MarketID,
		&i.ConditionID,
		&i.FreshnessState,
		&i.FreshnessReason,
		&i.BookHash,
		&i.UpstreamTimestamp,
		&i.ObservedAt,
		&i.Snapshot,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketsSyncCheckpoint = `-- name: GetMarketsSyncCheckpoint :one
SELECT source, upstream_source, stream, cursor, high_watermark, last_success_at, metadata, updated_at
FROM markets_sync_checkpoints
WHERE source = $1 AND stream = $2
`

type GetMarketsSyncCheckpointParams struct {
	Source string `json:"source"`
	Stream string `json:"stream"`
}

func (q *Queries) GetMarketsSyncCheckpoint(ctx context.Context, arg GetMarketsSyncCheckpointParams) (MarketsSyncCheckpoint, error) {
	row := q.db.QueryRow(ctx, getMarketsSyncCheckpoint, arg.Source, arg.Stream)
	var i MarketsSyncCheckpoint
	err := row.Scan(
		&i.Source,
		&i.UpstreamSource,
		&i.Stream,
		&i.Cursor,
		&i.HighWatermark,
		&i.LastSuccessAt,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMarketsHealthSnapshot = `-- name: InsertMarketsHealthSnapshot :exec
INSERT INTO markets_market_health_snapshots (
    market_id, token_id, algorithm_version, observed_at, freshness_state,
    components
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (market_id, token_id, algorithm_version, observed_at) DO NOTHING
`

type InsertMarketsHealthSnapshotParams struct {
	MarketID         string             `json:"market_id"`
	TokenID          string             `json:"token_id"`
	AlgorithmVersion string             `json:"algorithm_version"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	FreshnessState   string             `json:"freshness_state"`
	Components       []byte             `json:"components"`
}

func (q *Queries) InsertMarketsHealthSnapshot(ctx context.Context, arg InsertMarketsHealthSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertMarketsHealthSnapshot,
		arg.MarketID,
		arg.TokenID,
		arg.AlgorithmVersion,
		arg.ObservedAt,
		arg.FreshnessState,
		arg.Components,
	)
	return err
}

const insertMarketsHistoryPoint = `-- name: InsertMarketsHistoryPoint :exec
INSERT INTO markets_market_data_history (
    token_id, market_id, observed_at, price, derived, source
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (token_id, observed_at) DO UPDATE SET
    price = EXCLUDED.price,
    derived = EXCLUDED.derived,
    source = EXCLUDED.source
`

type InsertMarketsHistoryPointParams struct {
	TokenID    string             `json:"token_id"`
	MarketID   string             `json:"market_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Price      string             `json:"price"`
	Derived    bool               `json:"derived"`
	Source     string             `json:"source"`
}

func (q *Queries) InsertMarketsHistoryPoint(ctx context.Context, arg InsertMarketsHistoryPointParams) error {
	_, err := q.db.Exec(ctx, insertMarketsHistoryPoint,
		arg.TokenID,
		arg.MarketID,
		arg.ObservedAt,
		arg.Price,
		arg.Derived,
		arg.Source,
	)
	return err
}

const insertMarketsRawUpstreamEvent = `-- name: InsertMarketsRawUpstreamEvent :exec
INSERT INTO markets_raw_upstream_events (
    source, upstream_event_id, entity_type, entity_id, schema_version, payload,
    observed_at, expires_at, upstream_source, upstream_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (source, upstream_event_id) DO NOTHING
`

type InsertMarketsRawUpstreamEventParams struct {
	Source          string             `json:"source"`
	UpstreamEventID string             `json:"upstream_event_id"`
	EntityType      string             `json:"entity_type"`
	EntityID        string             `json:"entity_id"`
	SchemaVersion   string             `json:"schema_version"`
	Payload         []byte             `json:"payload"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UpstreamSource  string             `json:"upstream_source"`
	UpstreamID      string             `json:"upstream_id"`
}

func (q *Queries) InsertMarketsRawUpstreamEvent(ctx context.Context, arg InsertMarketsRawUpstreamEventParams) error {
	_, err := q.db.Exec(ctx, insertMarketsRawUpstreamEvent,
		arg.Source,
		arg.UpstreamEventID,
		arg.EntityType,
		arg.EntityID,
		arg.SchemaVersion,
		arg.Payload,
		arg.ObservedAt,
		arg.ExpiresAt,
		arg.UpstreamSource,
		arg.UpstreamID,
	)
	return err
}

const insertMarketsSignalEvidence = `-- name: InsertMarketsSignalEvidence :exec
INSERT INTO markets_signal_evidence (
    signal_id, evidence_index, kind, reference_id, observed_at, content_hash
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (signal_id, evidence_index) DO NOTHING
`

type InsertMarketsSignalEvidenceParams struct {
	SignalID      string             `json:"signal_id"`
	EvidenceIndex int32              `json:"evidence_index"`
	Kind          string             `json:"kind"`
	ReferenceID   string             `json:"reference_id"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	ContentHash   string             `json:"content_hash"`
}

func (q *Queries) InsertMarketsSignalEvidence(ctx context.Context, arg InsertMarketsSignalEvidenceParams) error {
	_, err := q.db.Exec(ctx, insertMarketsSignalEvidence,
		arg.SignalID,
		arg.EvidenceIndex,
		arg.Kind,
		arg.ReferenceID,
		arg.ObservedAt,
		arg.ContentHash,
	)
	return err
}

const listCatalogTokenMappings = `-- name: ListCatalogTokenMappings :many
SELECT o.upstream_token_id, o.market_id
FROM markets_catalog_outcomes o
INNER JOIN markets_catalog_markets m ON m.market_id = o.market_id
WHERE o.upstream_token_id <> ''
  AND m.status = 'open'
ORDER BY o.market_id, o.upstream_token_id
LIMIT $1 OFFSET $2
`

type ListCatalogTokenMappingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCatalogTokenMappingsRow struct {
	UpstreamTokenID string `json:"upstream_token_id"`
	MarketID        string `json:"market_id"`
}

func (q *Queries) ListCatalogTokenMappings(ctx context.Context, arg ListCatalogTokenMappingsParams) ([]ListCatalogTokenMappingsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogTokenMappings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogTokenMappingsRow{}
	for rows.Next() {
		var i ListCatalogTokenMappingsRow
		if err := rows.Scan(&i.UpstreamTokenID, &i.MarketID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsCatalogEventSummaries = `-- name: ListMarketsCatalogEventSummaries :many
SELECT
    e.event_id,
    e.slug,
    e.title,
    e.description,
    e.status,
    e.start_at,
    e.end_at,
    e.source,
    e.upstream_updated_at,
    e.content_hash,
    e.payload,
    e.observed_at,
    e.created_at,
    e.updated_at,
    COALESCE(m.market_count, 0)::INT AS market_count
FROM markets_catalog_events e
LEFT JOIN (
    SELECT event_id, COUNT(*)::INT AS market_count
    FROM markets_catalog_markets
    WHERE event_id IS NOT NULL AND event_id <> ''
    GROUP BY event_id
) m ON m.event_id = e.event_id
WHERE ($1::TEXT = '' OR e.status = $1)
ORDER BY COALESCE(e.end_at, 'infinity'::TIMESTAMPTZ), e.event_id
LIMIT $2 OFFSET $3
`

type ListMarketsCatalogEventSummariesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListMarketsCatalogEventSummariesRow struct {
	EventID           string             `json:"event_id"`
	Slug              string             `json:"slug"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Status            string             `json:"status"`
	StartAt           pgtype.Timestamptz `json:"start_at"`
	EndAt             pgtype.Timestamptz `json:"end_at"`
	Source            string             `json:"source"`
	UpstreamUpdatedAt pgtype.Timestamptz `json:"upstream_updated_at"`
	ContentHash       string             `json:"content_hash"`
	Payload           []byte             `json:"payload"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	MarketCount       int32              `json:"market_count"`
}

func (q *Queries) ListMarketsCatalogEventSummaries(ctx context.Context, arg ListMarketsCatalogEventSummariesParams) ([]ListMarketsCatalogEventSummariesRow, error) {
	rows, err := q.db.Query(ctx, listMarketsCatalogEventSummaries, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsCatalogEventSummariesRow{}
	for rows.Next() {
		var i ListMarketsCatalogEventSummariesRow
		if err := rows.Scan(
			&i.EventID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.Source,
			&i.UpstreamUpdatedAt,
			&i.ContentHash,
			&i.Payload,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MarketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsCatalogEvents = `-- name: ListMarketsCatalogEvents :many
SELECT event_id, id, upstream_id, upstream_source, slug, title, description, status, start_at, end_at, source, upstream_updated_at, content_hash, payload, observed_at, created_at, updated_at
FROM markets_catalog_events
WHERE ($1::TEXT = '' OR status = $1)
ORDER BY COALESCE(end_at, 'infinity'::TIMESTAMPTZ), event_id
LIMIT $2 OFFSET $3
`

type ListMarketsCatalogEventsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListMarketsCatalogEvents(ctx context.Context, arg ListMarketsCatalogEventsParams) ([]MarketsCatalogEvent, error) {
	rows, err := q.db.Query(ctx, listMarketsCatalogEvents, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketsCatalogEvent{}
	for rows.Next() {
		var i MarketsCatalogEvent
		if err := rows.Scan(
			&i.EventID,
			&i.ID,
			&i.UpstreamID,
			&i.UpstreamSource,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.Source,
			&i.UpstreamUpdatedAt,
			&i.ContentHash,
			&i.Payload,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsForEvent = `-- name: ListMarketsForEvent :many
SELECT market_id, id, upstream_id, upstream_source, event_id, condition_id, slug, question, description, status, end_at, enable_order_book, neg_risk, source, upstream_updated_at, content_hash, payload, observed_at, created_at, updated_at
FROM markets_catalog_markets
WHERE event_id = $1
ORDER BY market_id
`

func (q *Queries) ListMarketsForEvent(ctx context.Context, eventID pgtype.Text) ([]MarketsCatalogMarket, error) {
	rows, err := q.db.Query(ctx, listMarketsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketsCatalogMarket{}
	for rows.Next() {
		var i MarketsCatalogMarket
		if err := rows.Scan(
			&i.MarketID,
			&i.ID,
			&i.UpstreamID,
			&i.UpstreamSource,
			&i.EventID,
			&i.ConditionID,
			&i.Slug,
			&i.Question,
			&i.Description,
			&i.Status,
			&i.EndAt,
			&i.EnableOrderBook,
			&i.NegRisk,
			&i.Source,
			&i.UpstreamUpdatedAt,
			&i.ContentHash,
			&i.Payload,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsHistory = `-- name: ListMarketsHistory :many
SELECT token_id, market_id, observed_at, price, derived, source, created_at
FROM markets_market_data_history
WHERE token_id = $1 AND observed_at >= $2 AND observed_at <= $3
ORDER BY observed_at
LIMIT $4
`

type ListMarketsHistoryParams struct {
	TokenID      string             `json:"token_id"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) ListMarketsHistory(ctx context.Context, arg ListMarketsHistoryParams) ([]MarketsMarketDataHistory, error) {
	rows, err := q.db.Query(ctx, listMarketsHistory,
		arg.TokenID,
		arg.ObservedAt,
		arg.ObservedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketsMarketDataHistory{}
	for rows.Next() {
		var i MarketsMarketDataHistory
		if err := rows.Scan(
			&i.TokenID,
			&i.MarketID,
			&i.ObservedAt,
			&i.Price,
			&i.Derived,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsLiquidityObservations = `-- name: ListMarketsLiquidityObservations :many
SELECT market_id, token_id, bucket_start, bucket_end, total_depth, bid_depth, ask_depth, spread, epsilon, snapshot_hash, rule_version
FROM markets_liquidity_observations
WHERE market_id = $1 AND token_id = $2 AND bucket_end >= $3
ORDER BY bucket_end DESC
LIMIT $4
`

type ListMarketsLiquidityObservationsParams struct {
	MarketID  string             `json:"market_id"`
	TokenID   string             `json:"token_id"`
	BucketEnd pgtype.Timestamptz `json:"bucket_end"`
	Limit     int32              `json:"limit"`
}

type ListMarketsLiquidityObservationsRow struct {
	MarketID     string             `json:"market_id"`
	TokenID      string             `json:"token_id"`
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd    pgtype.Timestamptz `json:"bucket_end"`
	TotalDepth   string             `json:"total_depth"`
	BidDepth     string             `json:"bid_depth"`
	AskDepth     string             `json:"ask_depth"`
	Spread       pgtype.Text        `json:"spread"`
	Epsilon      string             `json:"epsilon"`
	SnapshotHash string             `json:"snapshot_hash"`
	RuleVersion  string             `json:"rule_version"`
}

func (q *Queries) ListMarketsLiquidityObservations(ctx context.Context, arg ListMarketsLiquidityObservationsParams) ([]ListMarketsLiquidityObservationsRow, error) {
	rows, err := q.db.Query(ctx, listMarketsLiquidityObservations,
		arg.MarketID,
		arg.TokenID,
		arg.BucketEnd,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsLiquidityObservationsRow{}
	for rows.Next() {
		var i ListMarketsLiquidityObservationsRow
		if err := rows.Scan(
			&i.MarketID,
			&i.TokenID,
			&i.BucketStart,
			&i.BucketEnd,
			&i.TotalDepth,
			&i.BidDepth,
			&i.AskDepth,
			&i.Spread,
			&i.Epsilon,
			&i.SnapshotHash,
			&i.RuleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsOutcomes = `-- name: ListMarketsOutcomes :many
SELECT outcome_id, id, upstream_id, upstream_source, market_id, upstream_token_id, outcome_index, name, price, winner, observed_at, created_at, updated_at
FROM markets_catalog_outcomes
WHERE market_id = $1
ORDER BY outcome_index
`

func (q *Queries) ListMarketsOutcomes(ctx context.Context, marketID string) ([]MarketsCatalogOutcome, error) {
	rows, err := q.db.Query(ctx, listMarketsOutcomes, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketsCatalogOutcome{}
	for rows.Next() {
		var i MarketsCatalogOutcome
		if err := rows.Scan(
			&i.OutcomeID,
			&i.ID,
			&i.UpstreamID,
			&i.UpstreamSource,
			&i.MarketID,
			&i.UpstreamTokenID,
			&i.OutcomeIndex,
			&i.Name,
			&i.Price,
			&i.Winner,
			&i.ObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsPriceObservations = `-- name: ListMarketsPriceObservations :many
SELECT market_id, token_id, bucket_start, bucket_end, price, best_bid, best_ask, spread, snapshot_hash, rule_version
FROM markets_price_observations
WHERE market_id = $1 AND token_id = $2 AND bucket_end >= $3
ORDER BY bucket_end DESC
LIMIT $4
`

type ListMarketsPriceObservationsParams struct {
	MarketID  string             `json:"market_id"`
	TokenID   string             `json:"token_id"`
	BucketEnd pgtype.Timestamptz `json:"bucket_end"`
	Limit     int32              `json:"limit"`
}

type ListMarketsPriceObservationsRow struct {
	MarketID     string             `json:"market_id"`
	TokenID      string             `json:"token_id"`
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd    pgtype.Timestamptz `json:"bucket_end"`
	Price        string             `json:"price"`
	BestBid      pgtype.Text        `json:"best_bid"`
	BestAsk      pgtype.Text        `json:"best_ask"`
	Spread       pgtype.Text        `json:"spread"`
	SnapshotHash string             `json:"snapshot_hash"`
	RuleVersion  string             `json:"rule_version"`
}

func (q *Queries) ListMarketsPriceObservations(ctx context.Context, arg ListMarketsPriceObservationsParams) ([]ListMarketsPriceObservationsRow, error) {
	rows, err := q.db.Query(ctx, listMarketsPriceObservations,
		arg.MarketID,
		arg.TokenID,
		arg.BucketEnd,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsPriceObservationsRow{}
	for rows.Next() {
		var i ListMarketsPriceObservationsRow
		if err := rows.Scan(
			&i.MarketID,
			&i.TokenID,
			&i.BucketStart,
			&i.BucketEnd,
			&i.Price,
			&i.BestBid,
			&i.BestAsk,
			&i.Spread,
			&i.SnapshotHash,
			&i.RuleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsSignalEvidenceForSignal = `-- name: ListMarketsSignalEvidenceForSignal :many
SELECT signal_id, evidence_index, kind, reference_id, observed_at, content_hash, created_at
FROM markets_signal_evidence
WHERE signal_id = $1
ORDER BY evidence_index
`

func (q *Queries) ListMarketsSignalEvidenceForSignal(ctx context.Context, signalID string) ([]MarketsSignalEvidence, error) {
	rows, err := q.db.Query(ctx, listMarketsSignalEvidenceForSignal, signalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketsSignalEvidence{}
	for rows.Next() {
		var i MarketsSignalEvidence
		if err := rows.Scan(
			&i.SignalID,
			&i.EvidenceIndex,
			&i.Kind,
			&i.ReferenceID,
			&i.ObservedAt,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsSignals = `-- name: ListMarketsSignals :many
SELECT signal_id, signal_type, market_id, state, rule_version, reason_codes, idempotency_key, created_at, expires_at, retracted_at, updated_at
FROM markets_market_signals
WHERE ($1::TEXT = '' OR market_id = $1)
ORDER BY created_at DESC, signal_id DESC
LIMIT $2 OFFSET $3
`

type ListMarketsSignalsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListMarketsSignals(ctx context.Context, arg ListMarketsSignalsParams) ([]MarketsMarketSignal, error) {
	rows, err := q.db.Query(ctx, listMarketsSignals, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketsMarketSignal{}
	for rows.Next() {
		var i MarketsMarketSignal
		if err := rows.Scan(
			&i.SignalID,
			&i.SignalType,
			&i.MarketID,
			&i.State,
			&i.RuleVersion,
			&i.ReasonCodes,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RetractedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseMarketsAdvisoryLock = `-- name: ReleaseMarketsAdvisoryLock :one
SELECT pg_advisory_unlock($1::BIGINT) AS released
`

func (q *Queries) ReleaseMarketsAdvisoryLock(ctx context.Context, dollar_1 int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseMarketsAdvisoryLock, dollar_1)
	var released bool
	err := row.Scan(&released)
	return released, err
}

const retractMarketsSignal = `-- name: RetractMarketsSignal :exec
WITH updated AS (
    UPDATE markets_market_signals
    SET state = 'retracted', retracted_at = $2, updated_at = NOW()
    WHERE signal_id = $1
)
INSERT INTO markets_signal_retractions (
    signal_id, reason_code, evidence_reference_id, retracted_at
) VALUES (
    $1, $3, $4, $2
)
ON CONFLICT (signal_id) DO UPDATE SET
    reason_code = EXCLUDED.reason_code,
    evidence_reference_id = EXCLUDED.evidence_reference_id,
    retracted_at = EXCLUDED.retracted_at
`

type RetractMarketsSignalParams struct {
	SignalID            string             `json:"signal_id"`
	RetractedAt         pgtype.Timestamptz `json:"retracted_at"`
	ReasonCode          string             `json:"reason_code"`
	EvidenceReferenceID string             `json:"evidence_reference_id"`
}

func (q *Queries) RetractMarketsSignal(ctx context.Context, arg RetractMarketsSignalParams) error {
	_, err := q.db.Exec(ctx, retractMarketsSignal,
		arg.SignalID,
		arg.RetractedAt,
		arg.ReasonCode,
		arg.EvidenceReferenceID,
	)
	return err
}

const tryMarketsAdvisoryLock = `-- name: TryMarketsAdvisoryLock :one
SELECT pg_try_advisory_lock($1::BIGINT) AS acquired
`

func (q *Queries) TryMarketsAdvisoryLock(ctx context.Context, dollar_1 int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryMarketsAdvisoryLock, dollar_1)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const upsertMarketsCatalogEvent = `-- name: UpsertMarketsCatalogEvent :one
INSERT INTO markets_catalog_events (
    event_id, slug, title, description, status, start_at, end_at, source,
    upstream_updated_at, content_hash, payload, observed_at,
    id, upstream_id, upstream_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    gen_random_uuid(), $13, $14
)
ON CONFLICT (event_id) DO UPDATE SET
    slug = EXCLUDED.slug,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    source = EXCLUDED.source,
    upstream_updated_at = EXCLUDED.upstream_updated_at,
    content_hash = EXCLUDED.content_hash,
    payload = EXCLUDED.payload,
    observed_at = EXCLUDED.observed_at,
    upstream_id = EXCLUDED.upstream_id,
    upstream_source = EXCLUDED.upstream_source,
    updated_at = NOW()
RETURNING event_id, id, upstream_id, upstream_source, slug, title, description, status, start_at, end_at, source, upstream_updated_at, content_hash, payload, observed_at, created_at, updated_at
`

type UpsertMarketsCatalogEventParams struct {
	EventID           string             `json:"event_id"`
	Slug              string             `json:"slug"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Status            string             `json:"status"`
	StartAt           pgtype.Timestamptz `json:"start_at"`
	EndAt             pgtype.Timestamptz `json:"end_at"`
	Source            string             `json:"source"`
	UpstreamUpdatedAt pgtype.Timestamptz `json:"upstream_updated_at"`
	ContentHash       string             `json:"content_hash"`
	Payload           []byte             `json:"payload"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	UpstreamID        string             `json:"upstream_id"`
	UpstreamSource    string             `json:"upstream_source"`
}

func (q *Queries) UpsertMarketsCatalogEvent(ctx context.Context, arg UpsertMarketsCatalogEventParams) (MarketsCatalogEvent, error) {
	row := q.db.QueryRow(ctx, upsertMarketsCatalogEvent,
		arg.EventID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.Source,
		arg.UpstreamUpdatedAt,
		arg.ContentHash,
		arg.Payload,
		arg.ObservedAt,
		arg.UpstreamID,
		arg.UpstreamSource,
	)
	var i MarketsCatalogEvent
	err := row.Scan(
		&i.EventID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Source,
		&i.UpstreamUpdatedAt,
		&i.ContentHash,
		&i.Payload,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketsCatalogMarket = `-- name: UpsertMarketsCatalogMarket :one
INSERT INTO markets_catalog_markets (
    market_id, event_id, condition_id, slug, question, description, status,
    end_at, enable_order_book, neg_risk, source, upstream_updated_at,
    content_hash, payload, observed_at,
    id, upstream_id, upstream_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    gen_random_uuid(), $16, $17
)
ON CONFLICT (market_id) DO UPDATE SET
    event_id = EXCLUDED.event_id,
    condition_id = EXCLUDED.condition_id,
    slug = EXCLUDED.slug,
    question = EXCLUDED.question,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    end_at = EXCLUDED.end_at,
    enable_order_book = EXCLUDED.enable_order_book,
    neg_risk = EXCLUDED.neg_risk,
    source = EXCLUDED.source,
    upstream_updated_at = EXCLUDED.upstream_updated_at,
    content_hash = EXCLUDED.content_hash,
    payload = EXCLUDED.payload,
    observed_at = EXCLUDED.observed_at,
    upstream_id = EXCLUDED.upstream_id,
    upstream_source = EXCLUDED.upstream_source,
    updated_at = NOW()
RETURNING market_id, id, upstream_id, upstream_source, event_id, condition_id, slug, question, description, status, end_at, enable_order_book, neg_risk, source, upstream_updated_at, content_hash, payload, observed_at, created_at, updated_at
`

type UpsertMarketsCatalogMarketParams struct {
	MarketID          string             `json:"market_id"`
	EventID           pgtype.Text        `json:"event_id"`
	ConditionID       string             `json:"condition_id"`
	Slug              string             `json:"slug"`
	Question          string             `json:"question"`
	Description       string             `json:"description"`
	Status            string             `json:"status"`
	EndAt             pgtype.Timestamptz `json:"end_at"`
	EnableOrderBook   bool               `json:"enable_order_book"`
	NegRisk           bool               `json:"neg_risk"`
	Source            string             `json:"source"`
	UpstreamUpdatedAt pgtype.Timestamptz `json:"upstream_updated_at"`
	ContentHash       string             `json:"content_hash"`
	Payload           []byte             `json:"payload"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	UpstreamID        string             `json:"upstream_id"`
	UpstreamSource    string             `json:"upstream_source"`
}

func (q *Queries) UpsertMarketsCatalogMarket(ctx context.Context, arg UpsertMarketsCatalogMarketParams) (MarketsCatalogMarket, error) {
	row := q.db.QueryRow(ctx, upsertMarketsCatalogMarket,
		arg.MarketID,
		arg.EventID,
		arg.ConditionID,
		arg.Slug,
		arg.Question,
		arg.Description,
		arg.Status,
		arg.EndAt,
		arg.EnableOrderBook,
		arg.NegRisk,
		arg.Source,
		arg.UpstreamUpdatedAt,
		arg.ContentHash,
		arg.Payload,
		arg.ObservedAt,
		arg.UpstreamID,
		arg.UpstreamSource,
	)
	var i MarketsCatalogMarket
	err := row.Scan(
		&i.MarketID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.EventID,
		&i.ConditionID,
		&i.Slug,
		&i.Question,
		&i.Description,
		&i.Status,
		&i.EndAt,
		&i.EnableOrderBook,
		&i.NegRisk,
		&i.Source,
		&i.UpstreamUpdatedAt,
		&i.ContentHash,
		&i.Payload,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketsCatalogOutcome = `-- name: UpsertMarketsCatalogOutcome :one
INSERT INTO markets_catalog_outcomes (
    outcome_id, market_id, upstream_token_id, outcome_index, name, price,
    winner, observed_at,
    id, upstream_id, upstream_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    gen_random_uuid(), $9, $10
)
ON CONFLICT (outcome_id) DO UPDATE SET
    upstream_token_id = EXCLUDED.upstream_token_id,
    outcome_index = EXCLUDED.outcome_index,
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    winner = EXCLUDED.winner,
    observed_at = EXCLUDED.observed_at,
    upstream_id = EXCLUDED.upstream_id,
    upstream_source = EXCLUDED.upstream_source,
    updated_at = NOW()
RETURNING outcome_id, id, upstream_id, upstream_source, market_id, upstream_token_id, outcome_index, name, price, winner, observed_at, created_at, updated_at
`

type UpsertMarketsCatalogOutcomeParams struct {
	OutcomeID       string             `json:"outcome_id"`
	MarketID        string             `json:"market_id"`
	UpstreamTokenID string             `json:"upstream_token_id"`
	OutcomeIndex    int32              `json:"outcome_index"`
	Name            string             `json:"name"`
	Price           pgtype.Text        `json:"price"`
	Winner          pgtype.Bool        `json:"winner"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	UpstreamID      string             `json:"upstream_id"`
	UpstreamSource  string             `json:"upstream_source"`
}

func (q *Queries) UpsertMarketsCatalogOutcome(ctx context.Context, arg UpsertMarketsCatalogOutcomeParams) (MarketsCatalogOutcome, error) {
	row := q.db.QueryRow(ctx, upsertMarketsCatalogOutcome,
		arg.OutcomeID,
		arg.MarketID,
		arg.UpstreamTokenID,
		arg.OutcomeIndex,
		arg.Name,
		arg.Price,
		arg.Winner,
		arg.ObservedAt,
		arg.UpstreamID,
		arg.UpstreamSource,
	)
	var i MarketsCatalogOutcome
	err := row.Scan(
		&i.OutcomeID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.MarketID,
		&i.UpstreamTokenID,
		&i.OutcomeIndex,
		&i.Name,
		&i.Price,
		&i.Winner,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketsCatalogRule = `-- name: UpsertMarketsCatalogRule :one
INSERT INTO markets_catalog_rules (
    market_id, description, resolution_source_name, resolution_source_url,
    content_hash, upstream_updated_at, observed_at,
    id, upstream_id, upstream_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    gen_random_uuid(), $8, $9
)
ON CONFLICT (market_id) DO UPDATE SET
    description = EXCLUDED.description,
    resolution_source_name = EXCLUDED.resolution_source_name,
    resolution_source_url = EXCLUDED.resolution_source_url,
    content_hash = EXCLUDED.content_hash,
    upstream_updated_at = EXCLUDED.upstream_updated_at,
    observed_at = EXCLUDED.observed_at,
    upstream_id = EXCLUDED.upstream_id,
    upstream_source = EXCLUDED.upstream_source,
    updated_at = NOW()
RETURNING market_id, id, upstream_id, upstream_source, description, resolution_source_name, resolution_source_url, content_hash, upstream_updated_at, observed_at, created_at, updated_at
`

type UpsertMarketsCatalogRuleParams struct {
	MarketID             string             `json:"market_id"`
	Description          string             `json:"description"`
	ResolutionSourceName string             `json:"resolution_source_name"`
	ResolutionSourceUrl  string             `json:"resolution_source_url"`
	ContentHash          string             `json:"content_hash"`
	UpstreamUpdatedAt    pgtype.Timestamptz `json:"upstream_updated_at"`
	ObservedAt           pgtype.Timestamptz `json:"observed_at"`
	UpstreamID           string             `json:"upstream_id"`
	UpstreamSource       string             `json:"upstream_source"`
}

func (q *Queries) UpsertMarketsCatalogRule(ctx context.Context, arg UpsertMarketsCatalogRuleParams) (MarketsCatalogRule, error) {
	row := q.db.QueryRow(ctx, upsertMarketsCatalogRule,
		arg.MarketID,
		arg.Description,
		arg.ResolutionSourceName,
		arg.ResolutionSourceUrl,
		arg.ContentHash,
		arg.UpstreamUpdatedAt,
		arg.ObservedAt,
		arg.UpstreamID,
		arg.UpstreamSource,
	)
	var i MarketsCatalogRule
	err := row.Scan(
		&i.MarketID,
		&i.ID,
		&i.UpstreamID,
		&i.UpstreamSource,
		&i.Description,
		&i.ResolutionSourceName,
		&i.ResolutionSourceUrl,
		&i.ContentHash,
		&i.UpstreamUpdatedAt,
		&i.ObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketsLatestBook = `-- name: UpsertMarketsLatestBook :one
INSERT INTO markets_market_data_latest (
    token_id, market_id, condition_id, freshness_state, freshness_reason,
    book_hash, upstream_timestamp, observed_at, snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (token_id) DO UPDATE SET
    market_id = EXCLUDED.market_id,
    condition_id = EXCLUDED.condition_id,
    freshness_state = EXCLUDED.freshness_state,
    freshness_reason = EXCLUDED.freshness_reason,
    book_hash = EXCLUDED.book_hash,
    upstream_timestamp = EXCLUDED.upstream_timestamp,
    observed_at = EXCLUDED.observed_at,
    snapshot = EXCLUDED.snapshot,
    updated_at = NOW()
RETURNING token_id, market_id, condition_id, freshness_state, freshness_reason, book_hash, upstream_timestamp, observed_at, snapshot, updated_at
`

type UpsertMarketsLatestBookParams struct {
	TokenID           string             `json:"token_id"`
	MarketID          string             `json:"market_id"`
	ConditionID       string             `json:"condition_id"`
	FreshnessState    string             `json:"freshness_state"`
	FreshnessReason   string             `json:"freshness_reason"`
	BookHash          string             `json:"book_hash"`
	UpstreamTimestamp pgtype.Timestamptz `json:"upstream_timestamp"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	Snapshot          []byte             `json:"snapshot"`
}

func (q *Queries) UpsertMarketsLatestBook(ctx context.Context, arg UpsertMarketsLatestBookParams) (MarketsMarketDataLatest, error) {
	row := q.db.QueryRow(ctx, upsertMarketsLatestBook,
		arg.TokenID,
		arg.MarketID,
		arg.ConditionID,
		arg.FreshnessState,
		arg.FreshnessReason,
		arg.BookHash,
		arg.UpstreamTimestamp,
		arg.ObservedAt,
		arg.Snapshot,
	)
	var i MarketsMarketDataLatest
	err := row.Scan(
		&i.TokenID,
		&i.MarketID,
		&i.ConditionID,
		&i.FreshnessState,
		&i.FreshnessReason,
		&i.BookHash,
		&i.UpstreamTimestamp,
		&i.ObservedAt,
		&i.Snapshot,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketsLiquidityObservation = `-- name: UpsertMarketsLiquidityObservation :exec
INSERT INTO markets_liquidity_observations (
    market_id, token_id, bucket_start, bucket_end, total_depth,
    bid_depth, ask_depth, spread, epsilon, snapshot_hash, rule_version, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (market_id, token_id, bucket_end) DO UPDATE SET
    total_depth = EXCLUDED.total_depth,
    bid_depth = EXCLUDED.bid_depth,
    ask_depth = EXCLUDED.ask_depth,
    spread = EXCLUDED.spread,
    epsilon = EXCLUDED.epsilon,
    snapshot_hash = EXCLUDED.snapshot_hash,
    rule_version = EXCLUDED.rule_version,
    expires_at = EXCLUDED.expires_at
`

type UpsertMarketsLiquidityObservationParams struct {
	MarketID     string             `json:"market_id"`
	TokenID      string             `json:"token_id"`
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd    pgtype.Timestamptz `json:"bucket_end"`
	TotalDepth   string             `json:"total_depth"`
	BidDepth     string             `json:"bid_depth"`
	AskDepth     string             `json:"ask_depth"`
	Spread       pgtype.Text        `json:"spread"`
	Epsilon      string             `json:"epsilon"`
	SnapshotHash string             `json:"snapshot_hash"`
	RuleVersion  string             `json:"rule_version"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertMarketsLiquidityObservation(ctx context.Context, arg UpsertMarketsLiquidityObservationParams) error {
	_, err := q.db.Exec(ctx, upsertMarketsLiquidityObservation,
		arg.MarketID,
		arg.TokenID,
		arg.BucketStart,
		arg.BucketEnd,
		arg.TotalDepth,
		arg.BidDepth,
		arg.AskDepth,
		arg.Spread,
		arg.Epsilon,
		arg.SnapshotHash,
		arg.RuleVersion,
		arg.ExpiresAt,
	)
	return err
}

const upsertMarketsPriceObservation = `-- name: UpsertMarketsPriceObservation :exec
INSERT INTO markets_price_observations (
    market_id, token_id, bucket_start, bucket_end, price,
    best_bid, best_ask, spread, snapshot_hash, rule_version, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (market_id, token_id, bucket_end) DO UPDATE SET
    price = EXCLUDED.price,
    best_bid = EXCLUDED.best_bid,
    best_ask = EXCLUDED.best_ask,
    spread = EXCLUDED.spread,
    snapshot_hash = EXCLUDED.snapshot_hash,
    rule_version = EXCLUDED.rule_version,
    expires_at = EXCLUDED.expires_at
`

type UpsertMarketsPriceObservationParams struct {
	MarketID     string             `json:"market_id"`
	TokenID      string             `json:"token_id"`
	BucketStart  pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd    pgtype.Timestamptz `json:"bucket_end"`
	Price        string             `json:"price"`
	BestBid      pgtype.Text        `json:"best_bid"`
	BestAsk      pgtype.Text        `json:"best_ask"`
	Spread       pgtype.Text        `json:"spread"`
	SnapshotHash string             `json:"snapshot_hash"`
	RuleVersion  string             `json:"rule_version"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertMarketsPriceObservation(ctx context.Context, arg UpsertMarketsPriceObservationParams) error {
	_, err := q.db.Exec(ctx, upsertMarketsPriceObservation,
		arg.MarketID,
		arg.TokenID,
		arg.BucketStart,
		arg.BucketEnd,
		arg.Price,
		arg.BestBid,
		arg.BestAsk,
		arg.Spread,
		arg.SnapshotHash,
		arg.RuleVersion,
		arg.ExpiresAt,
	)
	return err
}

const upsertMarketsRealtimeRecovery = `-- name: UpsertMarketsRealtimeRecovery :exec
INSERT INTO markets_realtime_recovery (
    token_id, stream_epoch, last_snapshot_hash, last_validated_at, updated_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT (token_id) DO UPDATE SET
    stream_epoch = EXCLUDED.stream_epoch,
    last_snapshot_hash = EXCLUDED.last_snapshot_hash,
    last_validated_at = EXCLUDED.last_validated_at,
    updated_at = NOW()
`

type UpsertMarketsRealtimeRecoveryParams struct {
	TokenID          string             `json:"token_id"`
	StreamEpoch      int64              `json:"stream_epoch"`
	LastSnapshotHash string             `json:"last_snapshot_hash"`
	LastValidatedAt  pgtype.Timestamptz `json:"last_validated_at"`
}

func (q *Queries) UpsertMarketsRealtimeRecovery(ctx context.Context, arg UpsertMarketsRealtimeRecoveryParams) error {
	_, err := q.db.Exec(ctx, upsertMarketsRealtimeRecovery,
		arg.TokenID,
		arg.StreamEpoch,
		arg.LastSnapshotHash,
		arg.LastValidatedAt,
	)
	return err
}

const upsertMarketsSignal = `-- name: UpsertMarketsSignal :one
INSERT INTO markets_market_signals (
    signal_id, signal_type, market_id, state, rule_version, reason_codes,
    idempotency_key, created_at, expires_at, retracted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (idempotency_key) DO UPDATE SET
    state = EXCLUDED.state,
    reason_codes = EXCLUDED.reason_codes,
    expires_at = EXCLUDED.expires_at,
    retracted_at = EXCLUDED.retracted_at,
    updated_at = NOW()
RETURNING signal_id, signal_type, market_id, state, rule_version, reason_codes, idempotency_key, created_at, expires_at, retracted_at, updated_at
`

type UpsertMarketsSignalParams struct {
	SignalID       string             `json:"signal_id"`
	SignalType     string             `json:"signal_type"`
	MarketID       string             `json:"market_id"`
	State          string             `json:"state"`
	RuleVersion    string             `json:"rule_version"`
	ReasonCodes    []byte             `json:"reason_codes"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RetractedAt    pgtype.Timestamptz `json:"retracted_at"`
}

func (q *Queries) UpsertMarketsSignal(ctx context.Context, arg UpsertMarketsSignalParams) (MarketsMarketSignal, error) {
	row := q.db.QueryRow(ctx, upsertMarketsSignal,
		arg.SignalID,
		arg.SignalType,
		arg.MarketID,
		arg.State,
		arg.RuleVersion,
		arg.ReasonCodes,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RetractedAt,
	)
	var i MarketsMarketSignal
	err := row.Scan(
		&i.SignalID,
		&i.SignalType,
		&i.MarketID,
		&i.State,
		&i.RuleVersion,
		&i.ReasonCodes,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RetractedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMarketsSyncCheckpoint = `-- name: UpsertMarketsSyncCheckpoint :one
INSERT INTO markets_sync_checkpoints (
    source, stream, cursor, high_watermark, last_success_at, metadata, upstream_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (source, stream) DO UPDATE SET
    cursor = EXCLUDED.cursor,
    high_watermark = EXCLUDED.high_watermark,
    last_success_at = EXCLUDED.last_success_at,
    metadata = EXCLUDED.metadata,
    upstream_source = EXCLUDED.upstream_source,
    updated_at = NOW()
RETURNING source, upstream_source, stream, cursor, high_watermark, last_success_at, metadata, updated_at
`

type UpsertMarketsSyncCheckpointParams struct {
	Source         string             `json:"source"`
	Stream         string             `json:"stream"`
	Cursor         string             `json:"cursor"`
	HighWatermark  pgtype.Timestamptz `json:"high_watermark"`
	LastSuccessAt  pgtype.Timestamptz `json:"last_success_at"`
	Metadata       []byte             `json:"metadata"`
	UpstreamSource string             `json:"upstream_source"`
}

func (q *Queries) UpsertMarketsSyncCheckpoint(ctx context.Context, arg UpsertMarketsSyncCheckpointParams) (MarketsSyncCheckpoint, error) {
	row := q.db.QueryRow(ctx, upsertMarketsSyncCheckpoint,
		arg.Source,
		arg.Stream,
		arg.Cursor,
		arg.HighWatermark,
		arg.LastSuccessAt,
		arg.Metadata,
		arg.UpstreamSource,
	)
	var i MarketsSyncCheckpoint
	err := row.Scan(
		&i.Source,
		&i.UpstreamSource,
		&i.Stream,
		&i.Cursor,
		&i.HighWatermark,
		&i.LastSuccessAt,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}
