// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbqueries

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceLedger struct {
	ID                    pgtype.UUID        `json:"id"`
	UserAddress           string             `json:"user_address"`
	DeltaAvailable        pgtype.Numeric     `json:"delta_available"`
	DeltaLocked           pgtype.Numeric     `json:"delta_locked"`
	BalanceAfterAvailable pgtype.Numeric     `json:"balance_after_available"`
	BalanceAfterLocked    pgtype.Numeric     `json:"balance_after_locked"`
	Reason                string             `json:"reason"`
	ReferenceType         pgtype.Text        `json:"reference_type"`
	ReferenceID           pgtype.Text        `json:"reference_id"`
	IdempotencyKey        string             `json:"idempotency_key"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ChainEvent struct {
	ID           int64              `json:"id"`
	BlockNumber  int64              `json:"block_number"`
	TxHash       string             `json:"tx_hash"`
	LogIndex     int32              `json:"log_index"`
	ContractAddr string             `json:"contract_addr"`
	EventName    string             `json:"event_name"`
	TemplateID   []byte             `json:"template_id"`
	EpochID      pgtype.Int8        `json:"epoch_id"`
	UserAddress  pgtype.Text        `json:"user_address"`
	Payload      []byte             `json:"payload"`
	BlockHash    []byte             `json:"block_hash"`
	IndexedAt    pgtype.Timestamptz `json:"indexed_at"`
}

type DestinationTransferIndexerState struct {
	ID        int16              `json:"id"`
	LastBlock int64              `json:"last_block"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DestinationUsdcTransfer struct {
	ID                     pgtype.UUID        `json:"id"`
	ChainID                int64              `json:"chain_id"`
	TokenAddress           string             `json:"token_address"`
	TxHash                 string             `json:"tx_hash"`
	LogIndex               int32              `json:"log_index"`
	FromAddress            string             `json:"from_address"`
	ToAddress              string             `json:"to_address"`
	Amount                 pgtype.Numeric     `json:"amount"`
	BlockNumber            int64              `json:"block_number"`
	BlockTimestamp         pgtype.Timestamptz `json:"block_timestamp"`
	MatchedFundingIntentID pgtype.UUID        `json:"matched_funding_intent_id"`
	MatchedExecutionID     pgtype.UUID        `json:"matched_execution_id"`
	CreditStatus           string             `json:"credit_status"`
	Provenance             string             `json:"provenance"`
	WebhookEventID         pgtype.UUID        `json:"webhook_event_id"`
	ProviderExecutionRef   pgtype.Text        `json:"provider_execution_ref"`
	MatchConfidence        pgtype.Numeric     `json:"match_confidence"`
	MatchMetadata          []byte             `json:"match_metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type Epoch struct {
	TemplateID         []byte             `json:"template_id"`
	EpochID            int64              `json:"epoch_id"`
	Status             string             `json:"status"`
	OpenAt             pgtype.Timestamptz `json:"open_at"`
	LockAt             pgtype.Timestamptz `json:"lock_at"`
	ResolveAt          pgtype.Timestamptz `json:"resolve_at"`
	OpenTxHash         pgtype.Text        `json:"open_tx_hash"`
	LockTxHash         pgtype.Text        `json:"lock_tx_hash"`
	ResolveTxHash      pgtype.Text        `json:"resolve_tx_hash"`
	Claimable          bool               `json:"claimable"`
	WinningOutcomeMask pgtype.Int4        `json:"winning_outcome_mask"`
	RefMode            bool               `json:"ref_mode"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FeeEvent struct {
	ID           int64              `json:"id"`
	TxHash       []byte             `json:"tx_hash"`
	LogIndex     int32              `json:"log_index"`
	MarketID     []byte             `json:"market_id"`
	TraderWallet []byte             `json:"trader_wallet"`
	TokenAddress []byte             `json:"token_address"`
	FeeAmount    pgtype.Numeric     `json:"fee_amount"`
	BlockNumber  int64              `json:"block_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type FeeRouteBatch struct {
	ID              int64              `json:"id"`
	BatchID         []byte             `json:"batch_id"`
	TokenAddress    []byte             `json:"token_address"`
	GrossAmount     pgtype.Numeric     `json:"gross_amount"`
	TreasuryAmount  pgtype.Numeric     `json:"treasury_amount"`
	RewardsAmount   pgtype.Numeric     `json:"rewards_amount"`
	CommunityAmount pgtype.Numeric     `json:"community_amount"`
	AllocationHash  []byte             `json:"allocation_hash"`
	TxHash          []byte             `json:"tx_hash"`
	LogIndex        int32              `json:"log_index"`
	BlockNumber     int64              `json:"block_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type FrontendHiddenTemplate struct {
	TemplateID []byte             `json:"template_id"`
	HiddenAt   pgtype.Timestamptz `json:"hidden_at"`
}

type FundingExecution struct {
	ID                      pgtype.UUID        `json:"id"`
	FundingIntentID         pgtype.UUID        `json:"funding_intent_id"`
	FundingRouteOptionID    pgtype.UUID        `json:"funding_route_option_id"`
	Provider                string             `json:"provider"`
	Status                  string             `json:"status"`
	WalletAddress           string             `json:"wallet_address"`
	ClientRouteExecutionID  pgtype.Text        `json:"client_route_execution_id"`
	SourceChainID           int64              `json:"source_chain_id"`
	SourceTokenAddress      string             `json:"source_token_address"`
	SourceAmount            pgtype.Numeric     `json:"source_amount"`
	DestinationChainID      int64              `json:"destination_chain_id"`
	DestinationTokenAddress string             `json:"destination_token_address"`
	ExpectedUsdcAmount      pgtype.Numeric     `json:"expected_usdc_amount"`
	MinUsdcAmount           pgtype.Numeric     `json:"min_usdc_amount"`
	SourceTxHash            pgtype.Text        `json:"source_tx_hash"`
	DestinationTxHash       pgtype.Text        `json:"destination_tx_hash"`
	ProviderStatus          []byte             `json:"provider_status"`
	RouteSnapshot           []byte             `json:"route_snapshot"`
	FailureCode             pgtype.Text        `json:"failure_code"`
	FailureMessage          pgtype.Text        `json:"failure_message"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type FundingIntent struct {
	ID                        pgtype.UUID        `json:"id"`
	UserAddress               string             `json:"user_address"`
	ClientNonce               pgtype.Text        `json:"client_nonce"`
	Status                    string             `json:"status"`
	TargetCurrency            string             `json:"target_currency"`
	TargetDisplayAmount       string             `json:"target_display_amount"`
	TargetAmountDecimal       string             `json:"target_amount_decimal"`
	TargetUsdcAmount          pgtype.Numeric     `json:"target_usdc_amount"`
	SettlementChainID         int64              `json:"settlement_chain_id"`
	SettlementTokenAddress    string             `json:"settlement_token_address"`
	SettlementReceiverAddress pgtype.Text        `json:"settlement_receiver_address"`
	SettlementTokenSymbol     string             `json:"settlement_token_symbol"`
	SettlementTokenDecimals   int32              `json:"settlement_token_decimals"`
	Mode                      string             `json:"mode"`
	RecommendedRouteID        pgtype.UUID        `json:"recommended_route_id"`
	SelectedRouteID           pgtype.UUID        `json:"selected_route_id"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	CreditedAmount            pgtype.Numeric     `json:"credited_amount"`
	CreditedAt                pgtype.Timestamptz `json:"credited_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FailureCode               pgtype.Text        `json:"failure_code"`
	FailureMessage            pgtype.Text        `json:"failure_message"`
}

type FundingRouteOption struct {
	ID                       pgtype.UUID        `json:"id"`
	FundingIntentID          pgtype.UUID        `json:"funding_intent_id"`
	Provider                 string             `json:"provider"`
	ProviderRouteID          string             `json:"provider_route_id"`
	SourceChainID            int64              `json:"source_chain_id"`
	SourceTokenAddress       string             `json:"source_token_address"`
	SourceTokenSymbol        pgtype.Text        `json:"source_token_symbol"`
	SourceTokenDecimals      pgtype.Int4        `json:"source_token_decimals"`
	SourceAmount             pgtype.Numeric     `json:"source_amount"`
	EstimatedUsdcReceived    pgtype.Numeric     `json:"estimated_usdc_received"`
	MinUsdcReceived          pgtype.Numeric     `json:"min_usdc_received"`
	EstimatedDurationSeconds pgtype.Int4        `json:"estimated_duration_seconds"`
	RouteScore               pgtype.Numeric     `json:"route_score"`
	RouteSnapshot            []byte             `json:"route_snapshot"`
	Status                   string             `json:"status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type FundingTransitionGuard struct {
	ID              int64              `json:"id"`
	FundingIntentID pgtype.UUID        `json:"funding_intent_id"`
	ToStatus        string             `json:"to_status"`
	IdempotencyKey  string             `json:"idempotency_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type FundingWebhookEvent struct {
	ID          pgtype.UUID        `json:"id"`
	Provider    string             `json:"provider"`
	EventID     string             `json:"event_id"`
	ExecutionID pgtype.UUID        `json:"execution_id"`
	EventType   pgtype.Text        `json:"event_type"`
	Payload     []byte             `json:"payload"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
}

type GooddollarUserStatus struct {
	Wallet         []byte             `json:"wallet"`
	GoodidVerified bool               `json:"goodid_verified"`
	RootWallet     []byte             `json:"root_wallet"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
}

type ImpactDailyMetric struct {
	Day             pgtype.Date    `json:"day"`
	GusdVolume      pgtype.Numeric `json:"gusd_volume"`
	GusdFees        pgtype.Numeric `json:"gusd_fees"`
	UniqueUsers     int32          `json:"unique_users"`
	VerifiedUsers   int32          `json:"verified_users"`
	RewardsClaimed  pgtype.Numeric `json:"rewards_claimed"`
	MarketsResolved int32          `json:"markets_resolved"`
}

type Incident struct {
	ID                   int64              `json:"id"`
	Title                string             `json:"title"`
	Severity             string             `json:"severity"`
	Status               string             `json:"status"`
	TemplateID           []byte             `json:"template_id"`
	Payload              []byte             `json:"payload"`
	OpenedAt             pgtype.Timestamptz `json:"opened_at"`
	NotifiedAt           pgtype.Timestamptz `json:"notified_at"`
	NotificationAttempts int32              `json:"notification_attempts"`
	LastError            pgtype.Text        `json:"last_error"`
}

type IndexerBlock struct {
	BlockNumber int64              `json:"block_number"`
	BlockHash   []byte             `json:"block_hash"`
	ParentHash  []byte             `json:"parent_hash"`
	IndexedAt   pgtype.Timestamptz `json:"indexed_at"`
}

type IndexerState struct {
	ID            int32              `json:"id"`
	LastBlock     int64              `json:"last_block"`
	LastBlockHash pgtype.Text        `json:"last_block_hash"`
	LastIndexedAt pgtype.Timestamptz `json:"last_indexed_at"`
	ReorgDepth    int32              `json:"reorg_depth"`
}

type KeeperExecution struct {
	ID                int64              `json:"id"`
	Action            string             `json:"action"`
	TemplateID        []byte             `json:"template_id"`
	EpochID           pgtype.Int8        `json:"epoch_id"`
	Result            string             `json:"result"`
	TxHash            pgtype.Text        `json:"tx_hash"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	ExecutedAt        pgtype.Timestamptz `json:"executed_at"`
	ScheduleID        pgtype.Int8        `json:"schedule_id"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	MinedAt           pgtype.Timestamptz `json:"mined_at"`
	GasUsed           pgtype.Int8        `json:"gas_used"`
	ReceiptJson       []byte             `json:"receipt_json"`
	ChainID           pgtype.Int8        `json:"chain_id"`
	Nonce             pgtype.Int8        `json:"nonce"`
	PreflightSnapshot []byte             `json:"preflight_snapshot"`
}

type KeeperSchedule struct {
	ID                int64              `json:"id"`
	TemplateID        []byte             `json:"template_id"`
	EpochID           pgtype.Int8        `json:"epoch_id"`
	Action            string             `json:"action"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	WindowEndAt       pgtype.Timestamptz `json:"window_end_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AttemptCount      int32              `json:"attempt_count"`
	LastError         pgtype.Text        `json:"last_error"`
	TxHash            pgtype.Text        `json:"tx_hash"`
	ClaimedBy         pgtype.Text        `json:"claimed_by"`
	ClaimedAt         pgtype.Timestamptz `json:"claimed_at"`
	PreflightSnapshot []byte             `json:"preflight_snapshot"`
}

type Ledger struct {
	TemplateID          []byte             `json:"template_id"`
	ActiveEpochID       int64              `json:"active_epoch_id"`
	LastResolvedEpochID int64              `json:"last_resolved_epoch_id"`
	RollingNextEpochID  int64              `json:"rolling_next_epoch_id"`
	HaltedAtEpochID     pgtype.Int8        `json:"halted_at_epoch_id"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type MarketEntry struct {
	ID              pgtype.UUID        `json:"id"`
	UserAddress     string             `json:"user_address"`
	MarketID        string             `json:"market_id"`
	OutcomeID       int32              `json:"outcome_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	FundingIntentID pgtype.UUID        `json:"funding_intent_id"`
	Status          string             `json:"status"`
	TxHash          pgtype.Text        `json:"tx_hash"`
	ChainID         pgtype.Int8        `json:"chain_id"`
	FailureCode     pgtype.Text        `json:"failure_code"`
	FailureMessage  pgtype.Text        `json:"failure_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MarketEpochOutcome struct {
	TemplateID     []byte             `json:"template_id"`
	EpochID        int64              `json:"epoch_id"`
	OutcomeIndex   int16              `json:"outcome_index"`
	PoolAmount     pgtype.Numeric     `json:"pool_amount"`
	ProbabilityBps int32              `json:"probability_bps"`
	MultiplierBps  int32              `json:"multiplier_bps"`
	UpdatedBlock   int64              `json:"updated_block"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MarketReadModel struct {
	TemplateID          []byte             `json:"template_id"`
	Slug                string             `json:"slug"`
	MarketType          int16              `json:"market_type"`
	Initialized         bool               `json:"initialized"`
	ExecutionMode       int16              `json:"execution_mode"`
	RollingPhase        int16              `json:"rolling_phase"`
	RollingHaltReason   int16              `json:"rolling_halt_reason"`
	ActiveEpochID       int64              `json:"active_epoch_id"`
	LastResolvedEpochID pgtype.Int8        `json:"last_resolved_epoch_id"`
	RollingNextEpochID  pgtype.Int8        `json:"rolling_next_epoch_id"`
	HaltedAtEpochID     pgtype.Int8        `json:"halted_at_epoch_id"`
	Status              string             `json:"status"`
	TotalPool           pgtype.Numeric     `json:"total_pool"`
	Volume              pgtype.Numeric     `json:"volume"`
	OutcomeCount        int16              `json:"outcome_count"`
	OutcomesJson        []byte             `json:"outcomes_json"`
	LastEventSeq        pgtype.Int8        `json:"last_event_seq"`
	LastIndexedBlock    int64              `json:"last_indexed_block"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type MarketSnapshot struct {
	TemplateID       []byte             `json:"template_id"`
	ActiveEpochID    int64              `json:"active_epoch_id"`
	Status           string             `json:"status"`
	TotalPool        pgtype.Numeric     `json:"total_pool"`
	Volume           pgtype.Numeric     `json:"volume"`
	OutcomeCount     int16              `json:"outcome_count"`
	LastIndexedBlock int64              `json:"last_indexed_block"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OracleFeedHealth struct {
	FeedID        string             `json:"feed_id"`
	Label         string             `json:"label"`
	RoundID       pgtype.Numeric     `json:"round_id"`
	PriceE8       pgtype.Numeric     `json:"price_e8"`
	PublishTime   pgtype.Timestamptz `json:"publish_time"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	Stale         bool               `json:"stale"`
	ErrorText     string             `json:"error_text"`
	Source        string             `json:"source"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PriceCandle struct {
	FeedID      string             `json:"feed_id"`
	IntervalSec int32              `json:"interval_sec"`
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	OpenE8      pgtype.Numeric     `json:"open_e8"`
	HighE8      pgtype.Numeric     `json:"high_e8"`
	LowE8       pgtype.Numeric     `json:"low_e8"`
	CloseE8     pgtype.Numeric     `json:"close_e8"`
	Source      string             `json:"source"`
	SampleCount int32              `json:"sample_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProbabilityPoint struct {
	TemplateID     []byte             `json:"template_id"`
	EpochID        int64              `json:"epoch_id"`
	Seq            int64              `json:"seq"`
	OutcomeIndex   int16              `json:"outcome_index"`
	BlockNumber    int64              `json:"block_number"`
	TxHash         pgtype.Text        `json:"tx_hash"`
	LogIndex       pgtype.Int4        `json:"log_index"`
	ProbabilityBps int32              `json:"probability_bps"`
	PoolAmount     pgtype.Numeric     `json:"pool_amount"`
	TotalPool      pgtype.Numeric     `json:"total_pool"`
	IndexedAt      pgtype.Timestamptz `json:"indexed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProviderToolsPolicy struct {
	ID        pgtype.UUID        `json:"id"`
	Provider  string             `json:"provider"`
	ToolKey   string             `json:"tool_key"`
	ToolType  string             `json:"tool_type"`
	Status    string             `json:"status"`
	RiskScore pgtype.Int4        `json:"risk_score"`
	Reason    pgtype.Text        `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RealtimeEvent struct {
	Seq         int64              `json:"seq"`
	Channel     string             `json:"channel"`
	Type        string             `json:"type"`
	Scope       string             `json:"scope"`
	UserAddress pgtype.Text        `json:"user_address"`
	TemplateID  []byte             `json:"template_id"`
	EpochID     pgtype.Int8        `json:"epoch_id"`
	BlockNumber pgtype.Int8        `json:"block_number"`
	TxHash      pgtype.Text        `json:"tx_hash"`
	LogIndex    pgtype.Int4        `json:"log_index"`
	Payload     []byte             `json:"payload"`
	DedupeKey   pgtype.Text        `json:"dedupe_key"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReferralBinding struct {
	RefereeWallet  []byte             `json:"referee_wallet"`
	ReferrerWallet []byte             `json:"referrer_wallet"`
	ReferralCode   string             `json:"referral_code"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReferralRewardEvent struct {
	ID             int64              `json:"id"`
	FeeEventID     int64              `json:"fee_event_id"`
	ReferrerWallet []byte             `json:"referrer_wallet"`
	TraderWallet   []byte             `json:"trader_wallet"`
	Level          int32              `json:"level"`
	Amount         pgtype.Numeric     `json:"amount"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReporterAuditLog struct {
	ID           int64              `json:"id"`
	SubmissionID pgtype.Int8        `json:"submission_id"`
	ActorID      pgtype.Int8        `json:"actor_id"`
	Action       string             `json:"action"`
	Reason       pgtype.Text        `json:"reason"`
	TxHash       []byte             `json:"tx_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ReporterIdentity struct {
	ID        int64              `json:"id"`
	Address   []byte             `json:"address"`
	Pubkey    []byte             `json:"pubkey"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReporterSubmission struct {
	ID           int64              `json:"id"`
	TemplateID   string             `json:"template_id"`
	EpochID      int64              `json:"epoch_id"`
	ReporterID   int64              `json:"reporter_id"`
	Outcome      []byte             `json:"outcome"`
	Evidence     []byte             `json:"evidence"`
	EvidenceHash []byte             `json:"evidence_hash"`
	Signature    []byte             `json:"signature"`
	Nonce        int64              `json:"nonce"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RewardClaim struct {
	ID                  int64              `json:"id"`
	Wallet              []byte             `json:"wallet"`
	RewardLedgerEventID pgtype.Int8        `json:"reward_ledger_event_id"`
	ClaimNonce          string             `json:"claim_nonce"`
	PayloadHash         []byte             `json:"payload_hash"`
	TxHash              []byte             `json:"tx_hash"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type RewardLedgerEvent struct {
	ID             int64              `json:"id"`
	Wallet         []byte             `json:"wallet"`
	QuestID        string             `json:"quest_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	TokenAddress   []byte             `json:"token_address"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RouteUpdateEvent struct {
	ID                 pgtype.UUID        `json:"id"`
	FundingExecutionID pgtype.UUID        `json:"funding_execution_id"`
	Provider           string             `json:"provider"`
	Status             pgtype.Text        `json:"status"`
	StepIndex          pgtype.Int4        `json:"step_index"`
	ProcessType        pgtype.Text        `json:"process_type"`
	ChainID            pgtype.Int8        `json:"chain_id"`
	TxHash             pgtype.Text        `json:"tx_hash"`
	Payload            []byte             `json:"payload"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SubmittedTransaction struct {
	TxHash         string             `json:"tx_hash"`
	UserAddress    string             `json:"user_address"`
	Action         string             `json:"action"`
	TemplateID     []byte             `json:"template_id"`
	EpochID        pgtype.Int8        `json:"epoch_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Template struct {
	TemplateID             []byte             `json:"template_id"`
	Slug                   string             `json:"slug"`
	MarketType             int16              `json:"market_type"`
	OutcomeCount           int16              `json:"outcome_count"`
	OracleMaxDelaySeconds  int64              `json:"oracle_max_delay_seconds"`
	OracleMaxConfidenceBps int32              `json:"oracle_max_confidence_bps"`
	Initialized            bool               `json:"initialized"`
	ExecutionMode          int16              `json:"execution_mode"`
	RollingPhase           int16              `json:"rolling_phase"`
	RollingHaltReason      int16              `json:"rolling_halt_reason"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type UserBalance struct {
	UserAddress   string             `json:"user_address"`
	UsdcAvailable pgtype.Numeric     `json:"usdc_available"`
	UsdcLocked    pgtype.Numeric     `json:"usdc_locked"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserPositionOutcome struct {
	UserAddress   string             `json:"user_address"`
	TemplateID    []byte             `json:"template_id"`
	EpochID       int64              `json:"epoch_id"`
	OutcomeIndex  int16              `json:"outcome_index"`
	StakeAmount   pgtype.Numeric     `json:"stake_amount"`
	ClaimedAmount pgtype.Numeric     `json:"claimed_amount"`
	Claimed       bool               `json:"claimed"`
	UpdatedBlock  int64              `json:"updated_block"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserWatchlist struct {
	UserAddress string             `json:"user_address"`
	TemplateID  []byte             `json:"template_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserWatchlistNonce struct {
	UserAddress string             `json:"user_address"`
	Nonce       int64              `json:"nonce"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WalletBalanceSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	FundingIntentID   pgtype.UUID        `json:"funding_intent_id"`
	UserAddress       string             `json:"user_address"`
	ChainID           int64              `json:"chain_id"`
	TokenAddress      string             `json:"token_address"`
	TokenSymbol       pgtype.Text        `json:"token_symbol"`
	TokenDecimals     pgtype.Int4        `json:"token_decimals"`
	BalanceAmount     pgtype.Numeric     `json:"balance_amount"`
	EstimatedUsdValue pgtype.Numeric     `json:"estimated_usd_value"`
	Source            string             `json:"source"`
	RawSnapshot       []byte             `json:"raw_snapshot"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WsConnection struct {
	ID             pgtype.UUID        `json:"id"`
	ServerID       string             `json:"server_id"`
	UserAddress    pgtype.Text        `json:"user_address"`
	IsOperator     bool               `json:"is_operator"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
	LastPingAt     pgtype.Timestamptz `json:"last_ping_at"`
	CloseCode      pgtype.Int4        `json:"close_code"`
	CloseReason    pgtype.Text        `json:"close_reason"`
}

type WsSubscription struct {
	ConnectionID pgtype.UUID        `json:"connection_id"`
	Channel      string             `json:"channel"`
	LastSeq      pgtype.Int8        `json:"last_seq"`
	SubscribedAt pgtype.Timestamptz `json:"subscribed_at"`
}
