// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChainEvent struct {
	ID           int64              `json:"id"`
	BlockNumber  int64              `json:"block_number"`
	TxHash       string             `json:"tx_hash"`
	LogIndex     int32              `json:"log_index"`
	ContractAddr string             `json:"contract_addr"`
	EventName    string             `json:"event_name"`
	TemplateID   []byte             `json:"template_id"`
	EpochID      pgtype.Int8        `json:"epoch_id"`
	UserAddress  pgtype.Text        `json:"user_address"`
	Payload      []byte             `json:"payload"`
	IndexedAt    pgtype.Timestamptz `json:"indexed_at"`
}

type Epoch struct {
	TemplateID         []byte             `json:"template_id"`
	EpochID            int64              `json:"epoch_id"`
	Status             string             `json:"status"`
	OpenAt             pgtype.Timestamptz `json:"open_at"`
	LockAt             pgtype.Timestamptz `json:"lock_at"`
	ResolveAt          pgtype.Timestamptz `json:"resolve_at"`
	OpenTxHash         pgtype.Text        `json:"open_tx_hash"`
	LockTxHash         pgtype.Text        `json:"lock_tx_hash"`
	ResolveTxHash      pgtype.Text        `json:"resolve_tx_hash"`
	Claimable          bool               `json:"claimable"`
	WinningOutcomeMask pgtype.Int4        `json:"winning_outcome_mask"`
	RefMode            bool               `json:"ref_mode"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Incident struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	Severity   string             `json:"severity"`
	Status     string             `json:"status"`
	TemplateID []byte             `json:"template_id"`
	Payload    []byte             `json:"payload"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
}

type IndexerState struct {
	ID            int32              `json:"id"`
	LastBlock     int64              `json:"last_block"`
	LastBlockHash pgtype.Text        `json:"last_block_hash"`
	LastIndexedAt pgtype.Timestamptz `json:"last_indexed_at"`
	ReorgDepth    int32              `json:"reorg_depth"`
}

type KeeperExecution struct {
	ID           int64              `json:"id"`
	Action       string             `json:"action"`
	TemplateID   []byte             `json:"template_id"`
	EpochID      pgtype.Int8        `json:"epoch_id"`
	Result       string             `json:"result"`
	TxHash       pgtype.Text        `json:"tx_hash"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ExecutedAt   pgtype.Timestamptz `json:"executed_at"`
}

type KeeperSchedule struct {
	ID          int64              `json:"id"`
	TemplateID  []byte             `json:"template_id"`
	EpochID     pgtype.Int8        `json:"epoch_id"`
	Action      string             `json:"action"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	WindowEndAt pgtype.Timestamptz `json:"window_end_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Ledger struct {
	TemplateID          []byte             `json:"template_id"`
	ActiveEpochID       int64              `json:"active_epoch_id"`
	LastResolvedEpochID int64              `json:"last_resolved_epoch_id"`
	RollingNextEpochID  int64              `json:"rolling_next_epoch_id"`
	HaltedAtEpochID     pgtype.Int8        `json:"halted_at_epoch_id"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Template struct {
	TemplateID             []byte             `json:"template_id"`
	Slug                   string             `json:"slug"`
	MarketType             int16              `json:"market_type"`
	OutcomeCount           int16              `json:"outcome_count"`
	OracleMaxDelaySeconds  int64              `json:"oracle_max_delay_seconds"`
	OracleMaxConfidenceBps int32              `json:"oracle_max_confidence_bps"`
	Initialized            bool               `json:"initialized"`
	ExecutionMode          int16              `json:"execution_mode"`
	RollingPhase           int16              `json:"rolling_phase"`
	RollingHaltReason      int16              `json:"rolling_halt_reason"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type UserWatchlist struct {
	UserAddress string             `json:"user_address"`
	TemplateID  []byte             `json:"template_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserWatchlistNonce struct {
	UserAddress string             `json:"user_address"`
	Nonce       int64              `json:"nonce"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
