// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package dbqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenIncidents = `-- name: CountOpenIncidents :one
SELECT COUNT(*)::bigint AS n
FROM incidents
WHERE status = 'open'
`

func (q *Queries) CountOpenIncidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIncidents)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*)::bigint AS n
FROM templates
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countTemplatesRollingHalted = `-- name: CountTemplatesRollingHalted :one
SELECT COUNT(*)::bigint AS n
FROM templates
WHERE rolling_phase = 3
`

func (q *Queries) CountTemplatesRollingHalted(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplatesRollingHalted)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const getEpoch = `-- name: GetEpoch :one
SELECT
    template_id,
    epoch_id,
    status,
    open_at,
    lock_at,
    resolve_at,
    open_tx_hash,
    lock_tx_hash,
    resolve_tx_hash,
    claimable,
    winning_outcome_mask,
    ref_mode,
    updated_at
FROM epochs
WHERE template_id = $1 AND epoch_id = $2
`

type GetEpochParams struct {
	TemplateID []byte `json:"template_id"`
	EpochID    int64  `json:"epoch_id"`
}

func (q *Queries) GetEpoch(ctx context.Context, arg GetEpochParams) (Epoch, error) {
	row := q.db.QueryRow(ctx, getEpoch, arg.TemplateID, arg.EpochID)
	var i Epoch
	err := row.Scan(
		&i.TemplateID,
		&i.EpochID,
		&i.Status,
		&i.OpenAt,
		&i.LockAt,
		&i.ResolveAt,
		&i.OpenTxHash,
		&i.LockTxHash,
		&i.ResolveTxHash,
		&i.Claimable,
		&i.WinningOutcomeMask,
		&i.RefMode,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndexerState = `-- name: GetIndexerState :one
SELECT id, last_block, last_block_hash, last_indexed_at, reorg_depth
FROM indexer_state
WHERE id = 1
`

func (q *Queries) GetIndexerState(ctx context.Context) (IndexerState, error) {
	row := q.db.QueryRow(ctx, getIndexerState)
	var i IndexerState
	err := row.Scan(
		&i.ID,
		&i.LastBlock,
		&i.LastBlockHash,
		&i.LastIndexedAt,
		&i.ReorgDepth,
	)
	return i, err
}

const getTemplateLedgerDetail = `-- name: GetTemplateLedgerDetail :one
SELECT
    t.template_id,
    t.slug,
    t.market_type,
    t.outcome_count,
    t.oracle_max_delay_seconds,
    t.oracle_max_confidence_bps,
    t.initialized,
    t.execution_mode,
    t.rolling_phase,
    t.rolling_halt_reason,
    t.updated_at,
    l.active_epoch_id,
    l.last_resolved_epoch_id,
    l.rolling_next_epoch_id,
    l.halted_at_epoch_id,
    l.updated_at AS ledger_updated_at
FROM templates t
LEFT JOIN ledgers l ON l.template_id = t.template_id
WHERE t.template_id = $1
`

type GetTemplateLedgerDetailRow struct {
	TemplateID             []byte             `json:"template_id"`
	Slug                   string             `json:"slug"`
	MarketType             int16              `json:"market_type"`
	OutcomeCount           int16              `json:"outcome_count"`
	OracleMaxDelaySeconds  int64              `json:"oracle_max_delay_seconds"`
	OracleMaxConfidenceBps int32              `json:"oracle_max_confidence_bps"`
	Initialized            bool               `json:"initialized"`
	ExecutionMode          int16              `json:"execution_mode"`
	RollingPhase           int16              `json:"rolling_phase"`
	RollingHaltReason      int16              `json:"rolling_halt_reason"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ActiveEpochID          pgtype.Int8        `json:"active_epoch_id"`
	LastResolvedEpochID    pgtype.Int8        `json:"last_resolved_epoch_id"`
	RollingNextEpochID     pgtype.Int8        `json:"rolling_next_epoch_id"`
	HaltedAtEpochID        pgtype.Int8        `json:"halted_at_epoch_id"`
	LedgerUpdatedAt        pgtype.Timestamptz `json:"ledger_updated_at"`
}

func (q *Queries) GetTemplateLedgerDetail(ctx context.Context, templateID []byte) (GetTemplateLedgerDetailRow, error) {
	row := q.db.QueryRow(ctx, getTemplateLedgerDetail, templateID)
	var i GetTemplateLedgerDetailRow
	err := row.Scan(
		&i.TemplateID,
		&i.Slug,
		&i.MarketType,
		&i.OutcomeCount,
		&i.OracleMaxDelaySeconds,
		&i.OracleMaxConfidenceBps,
		&i.Initialized,
		&i.ExecutionMode,
		&i.RollingPhase,
		&i.RollingHaltReason,
		&i.UpdatedAt,
		&i.ActiveEpochID,
		&i.LastResolvedEpochID,
		&i.RollingNextEpochID,
		&i.HaltedAtEpochID,
		&i.LedgerUpdatedAt,
	)
	return i, err
}

const getTemplateLedgerEpoch = `-- name: GetTemplateLedgerEpoch :one
SELECT
    t.template_id,
    t.slug,
    t.market_type,
    t.outcome_count,
    t.initialized,
    t.rolling_phase,
    t.rolling_halt_reason,
    l.active_epoch_id,
    l.last_resolved_epoch_id
FROM templates t
LEFT JOIN ledgers l ON l.template_id = t.template_id
WHERE t.template_id = $1
`

type GetTemplateLedgerEpochRow struct {
	TemplateID          []byte      `json:"template_id"`
	Slug                string      `json:"slug"`
	MarketType          int16       `json:"market_type"`
	OutcomeCount        int16       `json:"outcome_count"`
	Initialized         bool        `json:"initialized"`
	RollingPhase        int16       `json:"rolling_phase"`
	RollingHaltReason   int16       `json:"rolling_halt_reason"`
	ActiveEpochID       pgtype.Int8 `json:"active_epoch_id"`
	LastResolvedEpochID pgtype.Int8 `json:"last_resolved_epoch_id"`
}

func (q *Queries) GetTemplateLedgerEpoch(ctx context.Context, templateID []byte) (GetTemplateLedgerEpochRow, error) {
	row := q.db.QueryRow(ctx, getTemplateLedgerEpoch, templateID)
	var i GetTemplateLedgerEpochRow
	err := row.Scan(
		&i.TemplateID,
		&i.Slug,
		&i.MarketType,
		&i.OutcomeCount,
		&i.Initialized,
		&i.RollingPhase,
		&i.RollingHaltReason,
		&i.ActiveEpochID,
		&i.LastResolvedEpochID,
	)
	return i, err
}

const insertChainEvent = `-- name: InsertChainEvent :exec
INSERT INTO chain_events (
    block_number,
    tx_hash,
    log_index,
    contract_addr,
    event_name,
    template_id,
    epoch_id,
    user_address,
    payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tx_hash, log_index) DO NOTHING
`

type InsertChainEventParams struct {
	BlockNumber  int64       `json:"block_number"`
	TxHash       string      `json:"tx_hash"`
	LogIndex     int32       `json:"log_index"`
	ContractAddr string      `json:"contract_addr"`
	EventName    string      `json:"event_name"`
	TemplateID   []byte      `json:"template_id"`
	EpochID      pgtype.Int8 `json:"epoch_id"`
	UserAddress  pgtype.Text `json:"user_address"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) InsertChainEvent(ctx context.Context, arg InsertChainEventParams) error {
	_, err := q.db.Exec(ctx, insertChainEvent,
		arg.BlockNumber,
		arg.TxHash,
		arg.LogIndex,
		arg.ContractAddr,
		arg.EventName,
		arg.TemplateID,
		arg.EpochID,
		arg.UserAddress,
		arg.Payload,
	)
	return err
}

const listIncidents = `-- name: ListIncidents :many
SELECT
    id,
    title,
    severity,
    status,
    template_id,
    payload,
    opened_at
FROM incidents
ORDER BY opened_at DESC
LIMIT $1
`

func (q *Queries) ListIncidents(ctx context.Context, limit int32) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.TemplateID,
			&i.Payload,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeeperExecutions = `-- name: ListKeeperExecutions :many
SELECT
    id,
    action,
    template_id,
    epoch_id,
    result,
    tx_hash,
    error_message,
    executed_at
FROM keeper_executions
ORDER BY executed_at DESC
LIMIT $1
`

func (q *Queries) ListKeeperExecutions(ctx context.Context, limit int32) ([]KeeperExecution, error) {
	rows, err := q.db.Query(ctx, listKeeperExecutions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeeperExecution{}
	for rows.Next() {
		var i KeeperExecution
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TemplateID,
			&i.EpochID,
			&i.Result,
			&i.TxHash,
			&i.ErrorMessage,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeeperSchedule = `-- name: ListKeeperSchedule :many
SELECT
    id,
    template_id,
    epoch_id,
    action,
    scheduled_at,
    window_end_at,
    status,
    created_at
FROM keeper_schedule
ORDER BY scheduled_at DESC
LIMIT $1
`

func (q *Queries) ListKeeperSchedule(ctx context.Context, limit int32) ([]KeeperSchedule, error) {
	rows, err := q.db.Query(ctx, listKeeperSchedule, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeeperSchedule{}
	for rows.Next() {
		var i KeeperSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.EpochID,
			&i.Action,
			&i.ScheduledAt,
			&i.WindowEndAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT
    template_id,
    slug,
    market_type,
    outcome_count,
    initialized,
    execution_mode,
    rolling_phase,
    rolling_halt_reason,
    updated_at
FROM templates
ORDER BY slug
`

type ListTemplatesRow struct {
	TemplateID        []byte             `json:"template_id"`
	Slug              string             `json:"slug"`
	MarketType        int16              `json:"market_type"`
	OutcomeCount      int16              `json:"outcome_count"`
	Initialized       bool               `json:"initialized"`
	ExecutionMode     int16              `json:"execution_mode"`
	RollingPhase      int16              `json:"rolling_phase"`
	RollingHaltReason int16              `json:"rolling_halt_reason"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTemplates(ctx context.Context) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesRow{}
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.Slug,
			&i.MarketType,
			&i.OutcomeCount,
			&i.Initialized,
			&i.ExecutionMode,
			&i.RollingPhase,
			&i.RollingHaltReason,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesWithLedger = `-- name: ListTemplatesWithLedger :many
SELECT
    t.template_id,
    t.slug,
    t.market_type,
    t.outcome_count,
    t.initialized,
    t.execution_mode,
    t.rolling_phase,
    t.rolling_halt_reason,
    t.updated_at,
    l.active_epoch_id,
    l.last_resolved_epoch_id,
    l.rolling_next_epoch_id,
    l.halted_at_epoch_id
FROM templates t
LEFT JOIN ledgers l ON l.template_id = t.template_id
ORDER BY t.slug
`

type ListTemplatesWithLedgerRow struct {
	TemplateID          []byte             `json:"template_id"`
	Slug                string             `json:"slug"`
	MarketType          int16              `json:"market_type"`
	OutcomeCount        int16              `json:"outcome_count"`
	Initialized         bool               `json:"initialized"`
	ExecutionMode       int16              `json:"execution_mode"`
	RollingPhase        int16              `json:"rolling_phase"`
	RollingHaltReason   int16              `json:"rolling_halt_reason"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ActiveEpochID       pgtype.Int8        `json:"active_epoch_id"`
	LastResolvedEpochID pgtype.Int8        `json:"last_resolved_epoch_id"`
	RollingNextEpochID  pgtype.Int8        `json:"rolling_next_epoch_id"`
	HaltedAtEpochID     pgtype.Int8        `json:"halted_at_epoch_id"`
}

func (q *Queries) ListTemplatesWithLedger(ctx context.Context) ([]ListTemplatesWithLedgerRow, error) {
	rows, err := q.db.Query(ctx, listTemplatesWithLedger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesWithLedgerRow{}
	for rows.Next() {
		var i ListTemplatesWithLedgerRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.Slug,
			&i.MarketType,
			&i.OutcomeCount,
			&i.Initialized,
			&i.ExecutionMode,
			&i.RollingPhase,
			&i.RollingHaltReason,
			&i.UpdatedAt,
			&i.ActiveEpochID,
			&i.LastResolvedEpochID,
			&i.RollingNextEpochID,
			&i.HaltedAtEpochID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTemplateInitialized = `-- name: SetTemplateInitialized :exec
UPDATE templates
SET initialized = TRUE, updated_at = NOW()
WHERE template_id = $1
`

func (q *Queries) SetTemplateInitialized(ctx context.Context, templateID []byte) error {
	_, err := q.db.Exec(ctx, setTemplateInitialized, templateID)
	return err
}

const updateEpochLocked = `-- name: UpdateEpochLocked :exec
UPDATE epochs
SET
    status = 'locked',
    lock_tx_hash = $3,
    updated_at = NOW()
WHERE template_id = $1 AND epoch_id = $2
`

type UpdateEpochLockedParams struct {
	TemplateID []byte      `json:"template_id"`
	EpochID    int64       `json:"epoch_id"`
	LockTxHash pgtype.Text `json:"lock_tx_hash"`
}

func (q *Queries) UpdateEpochLocked(ctx context.Context, arg UpdateEpochLockedParams) error {
	_, err := q.db.Exec(ctx, updateEpochLocked, arg.TemplateID, arg.EpochID, arg.LockTxHash)
	return err
}

const updateEpochResolved = `-- name: UpdateEpochResolved :exec
UPDATE epochs
SET
    status = 'resolved',
    resolve_tx_hash = $3,
    claimable = TRUE,
    winning_outcome_mask = $4,
    ref_mode = $5,
    updated_at = NOW()
WHERE template_id = $1 AND epoch_id = $2
`

type UpdateEpochResolvedParams struct {
	TemplateID         []byte      `json:"template_id"`
	EpochID            int64       `json:"epoch_id"`
	ResolveTxHash      pgtype.Text `json:"resolve_tx_hash"`
	WinningOutcomeMask pgtype.Int4 `json:"winning_outcome_mask"`
	RefMode            bool        `json:"ref_mode"`
}

func (q *Queries) UpdateEpochResolved(ctx context.Context, arg UpdateEpochResolvedParams) error {
	_, err := q.db.Exec(ctx, updateEpochResolved,
		arg.TemplateID,
		arg.EpochID,
		arg.ResolveTxHash,
		arg.WinningOutcomeMask,
		arg.RefMode,
	)
	return err
}

const updateEpochResolvedCheckpointOnly = `-- name: UpdateEpochResolvedCheckpointOnly :exec
UPDATE epochs
SET
    status = 'resolved',
    resolve_tx_hash = $3,
    claimable = TRUE,
    updated_at = NOW()
WHERE template_id = $1 AND epoch_id = $2
`

type UpdateEpochResolvedCheckpointOnlyParams struct {
	TemplateID    []byte      `json:"template_id"`
	EpochID       int64       `json:"epoch_id"`
	ResolveTxHash pgtype.Text `json:"resolve_tx_hash"`
}

func (q *Queries) UpdateEpochResolvedCheckpointOnly(ctx context.Context, arg UpdateEpochResolvedCheckpointOnlyParams) error {
	_, err := q.db.Exec(ctx, updateEpochResolvedCheckpointOnly, arg.TemplateID, arg.EpochID, arg.ResolveTxHash)
	return err
}

const updateIndexerState = `-- name: UpdateIndexerState :exec
UPDATE indexer_state
SET
    last_block = $1,
    last_block_hash = $2,
    last_indexed_at = NOW(),
    reorg_depth = $3
WHERE id = 1
`

type UpdateIndexerStateParams struct {
	LastBlock     int64       `json:"last_block"`
	LastBlockHash pgtype.Text `json:"last_block_hash"`
	ReorgDepth    int32       `json:"reorg_depth"`
}

func (q *Queries) UpdateIndexerState(ctx context.Context, arg UpdateIndexerStateParams) error {
	_, err := q.db.Exec(ctx, updateIndexerState, arg.LastBlock, arg.LastBlockHash, arg.ReorgDepth)
	return err
}

const updateLedgerActiveEpoch = `-- name: UpdateLedgerActiveEpoch :exec
UPDATE ledgers
SET active_epoch_id = $2, updated_at = NOW()
WHERE template_id = $1
`

type UpdateLedgerActiveEpochParams struct {
	TemplateID    []byte `json:"template_id"`
	ActiveEpochID int64  `json:"active_epoch_id"`
}

func (q *Queries) UpdateLedgerActiveEpoch(ctx context.Context, arg UpdateLedgerActiveEpochParams) error {
	_, err := q.db.Exec(ctx, updateLedgerActiveEpoch, arg.TemplateID, arg.ActiveEpochID)
	return err
}

const updateLedgerAfterResolve = `-- name: UpdateLedgerAfterResolve :exec
UPDATE ledgers
SET last_resolved_epoch_id = $2, updated_at = NOW()
WHERE template_id = $1
`

type UpdateLedgerAfterResolveParams struct {
	TemplateID          []byte `json:"template_id"`
	LastResolvedEpochID int64  `json:"last_resolved_epoch_id"`
}

func (q *Queries) UpdateLedgerAfterResolve(ctx context.Context, arg UpdateLedgerAfterResolveParams) error {
	_, err := q.db.Exec(ctx, updateLedgerAfterResolve, arg.TemplateID, arg.LastResolvedEpochID)
	return err
}

const updateLedgerHaltedAt = `-- name: UpdateLedgerHaltedAt :exec
UPDATE ledgers
SET halted_at_epoch_id = $2, updated_at = NOW()
WHERE template_id = $1
`

type UpdateLedgerHaltedAtParams struct {
	TemplateID      []byte      `json:"template_id"`
	HaltedAtEpochID pgtype.Int8 `json:"halted_at_epoch_id"`
}

func (q *Queries) UpdateLedgerHaltedAt(ctx context.Context, arg UpdateLedgerHaltedAtParams) error {
	_, err := q.db.Exec(ctx, updateLedgerHaltedAt, arg.TemplateID, arg.HaltedAtEpochID)
	return err
}

const updateRollingHalted = `-- name: UpdateRollingHalted :exec
UPDATE templates
SET
    rolling_phase = 3,
    rolling_halt_reason = $2,
    updated_at = NOW()
WHERE template_id = $1
`

type UpdateRollingHaltedParams struct {
	TemplateID        []byte `json:"template_id"`
	RollingHaltReason int16  `json:"rolling_halt_reason"`
}

func (q *Queries) UpdateRollingHalted(ctx context.Context, arg UpdateRollingHaltedParams) error {
	_, err := q.db.Exec(ctx, updateRollingHalted, arg.TemplateID, arg.RollingHaltReason)
	return err
}

const upsertEpochOpened = `-- name: UpsertEpochOpened :exec
INSERT INTO epochs (
    template_id,
    epoch_id,
    status,
    open_at,
    lock_at,
    resolve_at,
    open_tx_hash
) VALUES ($1, $2, 'open', $3, $4, $5, $6)
ON CONFLICT (template_id, epoch_id) DO UPDATE SET
    status = 'open',
    open_at = EXCLUDED.open_at,
    lock_at = EXCLUDED.lock_at,
    resolve_at = EXCLUDED.resolve_at,
    open_tx_hash = EXCLUDED.open_tx_hash,
    updated_at = NOW()
`

type UpsertEpochOpenedParams struct {
	TemplateID []byte             `json:"template_id"`
	EpochID    int64              `json:"epoch_id"`
	OpenAt     pgtype.Timestamptz `json:"open_at"`
	LockAt     pgtype.Timestamptz `json:"lock_at"`
	ResolveAt  pgtype.Timestamptz `json:"resolve_at"`
	OpenTxHash pgtype.Text        `json:"open_tx_hash"`
}

func (q *Queries) UpsertEpochOpened(ctx context.Context, arg UpsertEpochOpenedParams) error {
	_, err := q.db.Exec(ctx, upsertEpochOpened,
		arg.TemplateID,
		arg.EpochID,
		arg.OpenAt,
		arg.LockAt,
		arg.ResolveAt,
		arg.OpenTxHash,
	)
	return err
}

const upsertLedgerRow = `-- name: UpsertLedgerRow :exec
INSERT INTO ledgers (template_id)
VALUES ($1)
ON CONFLICT (template_id) DO NOTHING
`

func (q *Queries) UpsertLedgerRow(ctx context.Context, templateID []byte) error {
	_, err := q.db.Exec(ctx, upsertLedgerRow, templateID)
	return err
}

const upsertTemplateFromUpsert = `-- name: UpsertTemplateFromUpsert :exec
INSERT INTO templates (
    template_id,
    slug,
    market_type,
    outcome_count,
    oracle_max_delay_seconds,
    oracle_max_confidence_bps
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (template_id) DO UPDATE SET
    slug = EXCLUDED.slug,
    market_type = EXCLUDED.market_type,
    outcome_count = EXCLUDED.outcome_count,
    oracle_max_delay_seconds = EXCLUDED.oracle_max_delay_seconds,
    oracle_max_confidence_bps = EXCLUDED.oracle_max_confidence_bps,
    updated_at = NOW()
`

type UpsertTemplateFromUpsertParams struct {
	TemplateID             []byte `json:"template_id"`
	Slug                   string `json:"slug"`
	MarketType             int16  `json:"market_type"`
	OutcomeCount           int16  `json:"outcome_count"`
	OracleMaxDelaySeconds  int64  `json:"oracle_max_delay_seconds"`
	OracleMaxConfidenceBps int32  `json:"oracle_max_confidence_bps"`
}

func (q *Queries) UpsertTemplateFromUpsert(ctx context.Context, arg UpsertTemplateFromUpsertParams) error {
	_, err := q.db.Exec(ctx, upsertTemplateFromUpsert,
		arg.TemplateID,
		arg.Slug,
		arg.MarketType,
		arg.OutcomeCount,
		arg.OracleMaxDelaySeconds,
		arg.OracleMaxConfidenceBps,
	)
	return err
}

const listEpochsByTemplate = `-- name: ListEpochsByTemplate :many
SELECT
    template_id,
    epoch_id,
    status,
    open_at,
    lock_at,
    resolve_at,
    open_tx_hash,
    lock_tx_hash,
    resolve_tx_hash,
    claimable,
    winning_outcome_mask,
    ref_mode,
    updated_at
FROM epochs
WHERE template_id = $1
ORDER BY epoch_id DESC
LIMIT $2
`

type ListEpochsByTemplateParams struct {
	TemplateID []byte `json:"template_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListEpochsByTemplate(ctx context.Context, arg ListEpochsByTemplateParams) ([]Epoch, error) {
	rows, err := q.db.Query(ctx, listEpochsByTemplate, arg.TemplateID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Epoch{}
	for rows.Next() {
		var i Epoch
		if err := rows.Scan(
			&i.TemplateID,
			&i.EpochID,
			&i.Status,
			&i.OpenAt,
			&i.LockAt,
			&i.ResolveAt,
			&i.OpenTxHash,
			&i.LockTxHash,
			&i.ResolveTxHash,
			&i.Claimable,
			&i.WinningOutcomeMask,
			&i.RefMode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChainEvents = `-- name: ListUserChainEvents :many
SELECT
    id,
    block_number,
    tx_hash,
    log_index,
    contract_addr,
    event_name,
    template_id,
    epoch_id,
    user_address,
    payload,
    indexed_at
FROM chain_events
WHERE user_address IS NOT NULL
  AND LOWER(user_address::text) = LOWER($1::text)
ORDER BY block_number DESC, log_index DESC
LIMIT $2
`

type ListUserChainEventsParams struct {
	UserAddress string `json:"user_address"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) ListUserChainEvents(ctx context.Context, arg ListUserChainEventsParams) ([]ChainEvent, error) {
	rows, err := q.db.Query(ctx, listUserChainEvents, arg.UserAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainEvent{}
	for rows.Next() {
		var i ChainEvent
		if err := rows.Scan(
			&i.ID,
			&i.BlockNumber,
			&i.TxHash,
			&i.LogIndex,
			&i.ContractAddr,
			&i.EventName,
			&i.TemplateID,
			&i.EpochID,
			&i.UserAddress,
			&i.Payload,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTemplateEpochPairs = `-- name: ListUserTemplateEpochPairs :many
SELECT DISTINCT template_id, epoch_id
FROM chain_events
WHERE user_address IS NOT NULL
  AND LOWER(user_address::text) = LOWER($1::text)
  AND event_name IN ('PositionDeposited', 'SideSwitched', 'Claimed')
  AND template_id IS NOT NULL
  AND epoch_id IS NOT NULL
ORDER BY template_id, epoch_id DESC
LIMIT $2
`

type ListUserTemplateEpochPairsParams struct {
	UserAddress string `json:"user_address"`
	Limit       int32  `json:"limit"`
}

type ListUserTemplateEpochPairsRow struct {
	TemplateID []byte `json:"template_id"`
	EpochID    int64  `json:"epoch_id"`
}

func (q *Queries) ListUserTemplateEpochPairs(ctx context.Context, arg ListUserTemplateEpochPairsParams) ([]ListUserTemplateEpochPairsRow, error) {
	rows, err := q.db.Query(ctx, listUserTemplateEpochPairs, arg.UserAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTemplateEpochPairsRow{}
	for rows.Next() {
		var i ListUserTemplateEpochPairsRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.EpochID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserClaimedEvents = `-- name: ListUserClaimedEvents :many
SELECT
    id,
    block_number,
    tx_hash,
    log_index,
    template_id,
    epoch_id,
    payload,
    indexed_at
FROM chain_events
WHERE user_address IS NOT NULL
  AND LOWER(user_address::text) = LOWER($1::text)
  AND event_name = 'Claimed'
  AND template_id IS NOT NULL
  AND epoch_id IS NOT NULL
ORDER BY block_number DESC, log_index DESC
LIMIT $2
`

type ListUserClaimedEventsParams struct {
	UserAddress string `json:"user_address"`
	Limit       int32  `json:"limit"`
}

type ListUserClaimedEventsRow struct {
	ID          int64              `json:"id"`
	BlockNumber int64              `json:"block_number"`
	TxHash      string             `json:"tx_hash"`
	LogIndex    int32              `json:"log_index"`
	TemplateID  []byte             `json:"template_id"`
	EpochID     int64              `json:"epoch_id"`
	Payload     []byte             `json:"payload"`
	IndexedAt   pgtype.Timestamptz `json:"indexed_at"`
}

func (q *Queries) ListUserClaimedEvents(ctx context.Context, arg ListUserClaimedEventsParams) ([]ListUserClaimedEventsRow, error) {
	rows, err := q.db.Query(ctx, listUserClaimedEvents, arg.UserAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserClaimedEventsRow{}
	for rows.Next() {
		var i ListUserClaimedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockNumber,
			&i.TxHash,
			&i.LogIndex,
			&i.TemplateID,
			&i.EpochID,
			&i.Payload,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTemplateFrontendHidden = `-- name: IsTemplateFrontendHidden :one
SELECT EXISTS (
    SELECT 1
    FROM frontend_hidden_templates
    WHERE template_id = $1
) AS hidden
`

func (q *Queries) IsTemplateFrontendHidden(ctx context.Context, templateID []byte) (bool, error) {
	row := q.db.QueryRow(ctx, isTemplateFrontendHidden, templateID)
	var hidden bool
	err := row.Scan(&hidden)
	return hidden, err
}

const addFrontendHidden = `-- name: AddFrontendHidden :exec
INSERT INTO frontend_hidden_templates (template_id)
VALUES ($1)
ON CONFLICT (template_id) DO NOTHING
`

func (q *Queries) AddFrontendHidden(ctx context.Context, templateID []byte) error {
	_, err := q.db.Exec(ctx, addFrontendHidden, templateID)
	return err
}

const removeFrontendHidden = `-- name: RemoveFrontendHidden :exec
DELETE FROM frontend_hidden_templates
WHERE template_id = $1
`

func (q *Queries) RemoveFrontendHidden(ctx context.Context, templateID []byte) error {
	_, err := q.db.Exec(ctx, removeFrontendHidden, templateID)
	return err
}

const listFrontendHidden = `-- name: ListFrontendHidden :many
SELECT
    template_id,
    hidden_at
FROM frontend_hidden_templates
ORDER BY hidden_at DESC
`

type ListFrontendHiddenRow struct {
	TemplateID []byte             `json:"template_id"`
	HiddenAt   pgtype.Timestamptz `json:"hidden_at"`
}

func (q *Queries) ListFrontendHidden(ctx context.Context) ([]ListFrontendHiddenRow, error) {
	rows, err := q.db.Query(ctx, listFrontendHidden)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrontendHiddenRow{}
	for rows.Next() {
		var i ListFrontendHiddenRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.HiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
