// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: v3_queries.sql

package dbqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFeeEvent = `-- name: InsertFeeEvent :one
INSERT INTO fee_events (tx_hash, log_index, market_id, trader_wallet, token_address, fee_amount, block_number)
VALUES ($1, $2, $3, $4, $5, $6::numeric, $7)
ON CONFLICT (tx_hash, log_index) DO UPDATE SET fee_amount = fee_events.fee_amount
RETURNING id
`

type InsertFeeEventParams struct {
	TxHash       []byte         `json:"tx_hash"`
	LogIndex     int32          `json:"log_index"`
	MarketID     []byte         `json:"market_id"`
	TraderWallet []byte         `json:"trader_wallet"`
	TokenAddress []byte         `json:"token_address"`
	Column6      pgtype.Numeric `json:"column_6"`
	BlockNumber  int64          `json:"block_number"`
}

func (q *Queries) InsertFeeEvent(ctx context.Context, arg InsertFeeEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFeeEvent,
		arg.TxHash,
		arg.LogIndex,
		arg.MarketID,
		arg.TraderWallet,
		arg.TokenAddress,
		arg.Column6,
		arg.BlockNumber,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReferralRewardEvent = `-- name: InsertReferralRewardEvent :exec
INSERT INTO referral_reward_events (fee_event_id, referrer_wallet, trader_wallet, level, amount, status)
VALUES ($1, $2, $3, $4, $5::numeric, 'claimable')
ON CONFLICT (fee_event_id, referrer_wallet, level) DO NOTHING
`

type InsertReferralRewardEventParams struct {
	FeeEventID     int64          `json:"fee_event_id"`
	ReferrerWallet []byte         `json:"referrer_wallet"`
	TraderWallet   []byte         `json:"trader_wallet"`
	Level          int32          `json:"level"`
	Column5        pgtype.Numeric `json:"column_5"`
}

func (q *Queries) InsertReferralRewardEvent(ctx context.Context, arg InsertReferralRewardEventParams) error {
	_, err := q.db.Exec(ctx, insertReferralRewardEvent,
		arg.FeeEventID,
		arg.ReferrerWallet,
		arg.TraderWallet,
		arg.Level,
		arg.Column5,
	)
	return err
}

const listFeeRouteBatches = `-- name: ListFeeRouteBatches :many
SELECT id, batch_id, token_address, gross_amount::text, treasury_amount::text,
       rewards_amount::text, community_amount::text, tx_hash, log_index, block_number, created_at
FROM fee_route_batches
ORDER BY created_at DESC
LIMIT $1
`

type ListFeeRouteBatchesRow struct {
	ID              int64              `json:"id"`
	BatchID         []byte             `json:"batch_id"`
	TokenAddress    []byte             `json:"token_address"`
	GrossAmount     string             `json:"gross_amount"`
	TreasuryAmount  string             `json:"treasury_amount"`
	RewardsAmount   string             `json:"rewards_amount"`
	CommunityAmount string             `json:"community_amount"`
	TxHash          []byte             `json:"tx_hash"`
	LogIndex        int32              `json:"log_index"`
	BlockNumber     int64              `json:"block_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListFeeRouteBatches(ctx context.Context, limit int32) ([]ListFeeRouteBatchesRow, error) {
	rows, err := q.db.Query(ctx, listFeeRouteBatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeeRouteBatchesRow{}
	for rows.Next() {
		var i ListFeeRouteBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.TokenAddress,
			&i.GrossAmount,
			&i.TreasuryAmount,
			&i.RewardsAmount,
			&i.CommunityAmount,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralEarnings = `-- name: ListReferralEarnings :many
SELECT level, amount::text, status, created_at
FROM referral_reward_events
WHERE referrer_wallet = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReferralEarningsParams struct {
	ReferrerWallet []byte `json:"referrer_wallet"`
	Limit          int32  `json:"limit"`
}

type ListReferralEarningsRow struct {
	Level     int32              `json:"level"`
	Amount    string             `json:"amount"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListReferralEarnings(ctx context.Context, arg ListReferralEarningsParams) ([]ListReferralEarningsRow, error) {
	rows, err := q.db.Query(ctx, listReferralEarnings, arg.ReferrerWallet, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReferralEarningsRow{}
	for rows.Next() {
		var i ListReferralEarningsRow
		if err := rows.Scan(
			&i.Level,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReporterSubmissionsPending = `-- name: ListReporterSubmissionsPending :many
SELECT id, template_id, epoch_id, outcome, evidence, status
FROM reporter_submissions
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT 100
`

type ListReporterSubmissionsPendingRow struct {
	ID         int64  `json:"id"`
	TemplateID string `json:"template_id"`
	EpochID    int64  `json:"epoch_id"`
	Outcome    []byte `json:"outcome"`
	Evidence   []byte `json:"evidence"`
	Status     string `json:"status"`
}

func (q *Queries) ListReporterSubmissionsPending(ctx context.Context) ([]ListReporterSubmissionsPendingRow, error) {
	rows, err := q.db.Query(ctx, listReporterSubmissionsPending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReporterSubmissionsPendingRow{}
	for rows.Next() {
		var i ListReporterSubmissionsPendingRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.EpochID,
			&i.Outcome,
			&i.Evidence,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
