name: Verify

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Repository
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
